helmfile/helmfile

pkg/helmexec/exec.go

Closes https://github.com/roboll/helmfile/issues/2127

[fix] unclosed file stream when creating temporary decrypted files

---

Dockerfile
Makefile

@mumoshu Sorry for the bug with Dockerfile :-(
`TAG ?=` is to used locally to run something like this
```
make image TAG=dev
docker build -t quay.io/github/helmfile:dev .
```

[fix] bump go 1.18 & optional TAG definition in makefile

---

main.go

Fixed: https://github.com/helmfile/helmfile/issues/30

fix output-dir issue

---

pkg/state/temp.go

When using non-existent custom temporary dir with `HELMFILE_TEMPDIR`, raised errors are not clear. I propose that we try to create automatically the custom temp dir.
```
HELMFILE_TEMPDIR=.helmfile
```
```
in ./helmfile.yaml: in .helmfiles[2]: in ./helmfile.yaml: 2 errors:
err 0: open .helmfile/staging-x-values-6b4cd67d8b: no such file or directory
err 1: open .helmfile/staging-x-values-5f97d6746b: no such file or directory
```

Fix non-existent custom temp dir

---

pkg/app/run.go
pkg/state/state.go
pkg/state/temp_test.go

This fixes a bug in `helmfile deps`.
When chartify is involved due to the use of `forceNamespace`, `strategicMergePatches`, `jsonPatches`, and so on, we had been internally mutating the Release.Chart with the path to the local temporary directory that contains the modified version of the chart.
That resulted in us unintentionally making `helmfile deps` to remove entries for the chart being modified out of helmfile.lock file, which resulted in issues like #2110.
To be clear, although the original issue is reported to occur for `strategicMergePatches`, I believe that it occurered also for any remote charts using `jsonPatches` and `forceNamespace` too.
I also believe this has been an issue since our introduction of chartify (maybe a year or so ago??), and I guess why it took so much time to …

Fix helmfile deps not to remove entries for charts that are being chartified

---

main.go
pkg/app/app.go
pkg/app/app_test.go
pkg/app/config.go
pkg/app/diff_test.go
pkg/app/validate_config.go
pkg/state/state.go

Since helm-diff has added an ability to auto-detect the term to decide if it should output with color or not, helmfile had been defaulted to no-color.
This resoloves that, by adding a term-detection logic that is same as helm-diff.
As a part of this work, I have also implemented a new global flag `--color`, which is used for forcing color without relying on the term-detection logic implemented in helmfile or explicitly setting the HELM_DIFF_COLOR envvar. I hope it is useful for folks.
Ref https://github.com/roboll/helmfile/issues/2043

feat: Auto-detect term for coloring helm-diff output

---

README.md
pkg/tmpl/context_funcs.go
pkg/tmpl/context_funcs_test.go

rename execEnvs to envExec

---

main.go
pkg/app/app.go
pkg/app/config.go

Chart using `.Capabilities` helm  built-in object cannot be sync as `sync` command does not accept `--validate` Options
This PR permit usage of `--validate` options with sync command
```yaml
{{- if and .Values.alertmanager.enabled .Values.alertmanager.ingress.enabled }}
{{- $servicePort := 9093 -}}
{{- $ingressPath := .Values.alertmanager.ingress.path -}}
{{- $serviceName := printf "%s-%s" "vmalertmanager" (include "victoria-metrics-k8s-stack.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- $ingressPathType := .Values.alertmanager.ingress.pathType | default "" -}}
{{- $extraPaths := .Values.alertmanager.ingress.extraPaths -}}
{{- $newAPI := .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
{{- if $newAPI -}}
apiVersion: networking.k8s.io/v1
{{- else if …
```

feat: allow --validate on sync command

---

pkg/remote/remote.go
pkg/remote/remote_test.go
pkg/state/envvals_loader_test.go
pkg/state/storage.go

The releases and environment section allow for values files on the local
disk.
This enhancement allows for referencing remote (go-getter) files to be
fetched, cached and referenced.
Example:
```yaml
repositories:
- name: "incubator"
url: "https://charts.helm.sh/incubator/"
releases:
- name: "test"
namespace: "test"
chart: "incubator/raw"
version: "0.1.0"
missingFileHandler: Debug
values:
- "git::https://github.com/helm/charts.git@raw/ci/values.yaml"
```
In addition when fetching a remote git source with a ssh key the ssh key
will not be part of the caching folder name. This avoids two problems:
1. Don't leak sensitive information in the name of the caching folder
2. Base64 encoded SSH keys are very long. On some file systems the max
lenght of the directory name is hit when using the full …

Adds feature to fetch release values and secret values from remote

---

pkg/state/state.go
pkg/state/state_test.go

Support for the missing `KubeVersion` flag on Helm-diff was added in this PR: https://github.com/databus23/helm-diff/pull/386.
Helm-diff will append these flags to `helm template`.
Changes:
* Added unit test for `state.flagsForDiff`
* Fix `appendApiVersionsFlags` to check `Helmstate` values if `ReleaseSpec` values aren't set.

chore(state): Append Api Versions flags to helm-diff

---

docs/proposals/towards-1.0.md

@itscaro @yxxhero I have some ideas about how we proceed to 1.0. WDYT?
// BTW, once we reach 1.0, I have an idea to make the user experience of writing and reading helmfile configs more great, by using Starlark as the basis for Helmfile config syntax 😃 Following the policy described in this proposal, it will be added as a secondary config syntax and we'll keep current yaml+gotemplate based syntax as is, at least while in 1.x.

Add proposals about two breaking changes before we cut Helmfile 1.0

---

README.md

`stable/prometheus` is DEPRECATED and moved to `prometheus-community/prometheus`.
see https://github.com/helm/charts/blob/master/stable/prometheus/README.md?plain=1#L3
So, I fixed "Getting Started" in README.md.

Fix deprecated chart in Getting Started

---

.github/workflows/ci.yaml

fix ci test error
```
make build build-test-tools
shell: /usr/bin/bash -e {0}
env:
GOROOT: /opt/hostedtoolcache/go/1.18.[3](https://github.com/helmfile/helmfile/runs/6953513978?check_suite_focus=true#step:6:3)/x6[4](https://github.com/helmfile/helmfile/runs/6953513978?check_suite_focus=true#step:6:4)
fatal: No names found, cannot describe anything.
go build -ldflags '-X github.com/helmfile/helmfile/pkg/app/version.Version=' 
go build test/diff-yamls/diff-yamls.go
go build test/yamldiff/yamldiff.go
```
version is nil

fix ci test error

---

pkg/app/app_test.go
pkg/app/constants_test.go
pkg/helmexec/context_test.go
pkg/helmexec/exec_test.go
pkg/state/state_test.go
pkg/tmpl/context_funcs_test.go
pkg/tmpl/context_tmpl_test.go
test/e2e/template/helmfile/tmpl_test.go

This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv

test: use `T.Setenv` to set env vars in tests

---

.github/ISSUE_TEMPLATE/bug.yml

so that it might be even more clear if the reported problem has been introduced by the prev release or a long-standing one which existed for longer time period.

Include the working helmfile ver in the bug report

---

cmd/root.go

revert environment long option from --env to --environment

---

docs/index.md
pkg/tmpl/context.go
pkg/tmpl/context_funcs.go
pkg/tmpl/context_funcs_test.go
test/e2e/template/helmfile/tmpl_test.go

Implementing feature to read directories from provided directory path based on Idea here:
https://github.com/helmfile/helmfile/discussions/253
Within the README.md I have also documented the readDir function which was not documented but available for usage.

Implement readDirEntries method

---

cmd/apply.go

fix #265 
selector flag defined in cmd/apply.go overrides the one from cmd/root.go

remove selector override in cmd/apply

---

pkg/app/diff_test.go
pkg/app/testdata/app_diff_test_1/upgrade_when_foo_needs_bar_with_context_override
pkg/app/testdata/app_diff_test_1/upgrade_when_releaseb_needs_releasea_with_aws_context
pkg/state/state.go

Fix an issue that causes `needs:` dependency errors when using kube context with slashes in it. This works by joining all components of ID except last two (`namespace` and `name`).
Assumes `namespace` and `name` cannot contain slashes.
Fixes https://github.com/helmfile/helmfile/issues/203

fix: needs error with context that includes slash

---

pkg/state/storage.go
pkg/state/storage_test.go

If remote file isn't present in repo we will add it anyway to the files list and check `if len(files) == 0 {` never will be true. That leads to missing section with `MissingFileHandler`.
That fix check that cloned file actually exists. In that case if we add a link to non-existing remote file `MissingFileHandler` will be called as expected.

Add file existence check for remote values

---

README.md
docs/index.md

AUR package is officially deprecated now, see https://github.com/helmfile/helmfile/discussions/278
I also removed trailing `or` things because they are not consistent anyway and don't add any value

Update ArchLinux installation instructions

---

pkg/app/app.go
pkg/app/app_list_test.go
pkg/app/app_test.go
pkg/app/testdata/app_list_test/default_environment_includes_all_releases
pkg/app/testdata/app_list_test/fail_on_unknown_environment
pkg/app/testdata/app_list_test/filters_releases_for_environment_used_in_multiple_files
pkg/app/testdata/app_list_test/filters_releases_for_environment_used_in_one_file_only
pkg/app/testdata/app_list_test/list_releases_matching_selector_and_environment

Fixing releases being included which do not match the environment requested, which is a regression introduced by #234. The issue remains when Helmfile state values are supplied, which is not a regression and will be addressed separately.
Partial resolution for #271

Fix Inclusion of Releases for Other Environments

---

pkg/tmpl/file_renderer.go
test/e2e/template/helmfile/tmpl_test.go

I just created a naked helmfile.yaml with readDirEntries and it crashed.
```
environments:
{{ range $index,$item := readDirEntries "./environments" }}
{{$item}}:
{{ end }}
```
```
Error: in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:2:27: executing "stringTemplate" at <readDirEntries "./environments">: error calling readDirEntries: runtime error: invalid memory address or nil pointer dereference
```
I added the template tests at `test/e2e/template/helmfile/tmpl_test.go` to a full FileRenderer test and it crashed in a similar way.
Basically when a new FileRenderer is created nothing is set in the Contexts readDir pointer so it is a dangling pointer there.
I just set the default to `os.ReadDir`

Fix for readDir selection, currently any template that uses readDir* functions seems to break

---

cmd/apply.go

We would like to add back --set flag to apply subcommand, which was
accidentally removed after switching to cobra (#234)
Signed-off-by: Michal Jura <mjura@suse.com>

Bring back --set flag to apply subcommand

---

pkg/config/diff.go

As part of the Cobra upgrade, the diff output option had been hard coded return an empty string. This fixes the issue by using the value in the struct.
Signed-off-by: Michael Lorant <michael.lorant@fairfaxmedia.com.au>

fix: return diff output config value

---

pkg/config/diff.go

As part of the Cobra upgrade, the diff `context` option had been hard coded to a value of `0`. This fixes the issue by using the value in the struct.
Signed-off-by: Michael Lorant <michael.lorant@fairfaxmedia.com.au>

fix: return diff context config value

---

cmd/apply.go
cmd/root.go
cmd/status.go
docs/index.md

an improvement for cobra
`StringSliceVar` defines a string flag with specified name, default value, and usage string. The argument p points to a []string variable in which to store the value of the flag. Compared to StringArray flags, StringSlice flags take comma-separated value as arguments and split them accordingly. 
`StringArrayVar` defines a string flag with specified name, default value, and usage string. The argument p points to a []string variable in which to store the values of the multiple flags. The value of each argument will not try to be separated by comma. Use a StringSlice for that.
@mumoshu

Improve some multi-value flags to accept comma-separated values

---

README.md
USERS.md

I've noticed a bit late that there isn't any "OSS" in Jenkins name.
Signed-off-by: Hervé Le Meur <hlemeur@cloudbees.com>

chore: remove 'OSS' from Jenkins name

---

cmd/list.go
pkg/app/app.go
pkg/app/app_list_test.go
pkg/app/app_test.go
pkg/app/config.go
pkg/config/list.go

This changes list command so it doesn't run withPreparedCharts, and just lists releases instead.
See discussion https://github.com/helmfile/helmfile/discussions/344 for reasoning.
This might break environments which relied on `list` having to build everything - I can add a backwards compatible opt flag if that's an issue
Add `--skip-charts` flag to `list` subcommand, to only list releases without preparing and templating charts for them

feat: dont prepare on list

---

cmd/root.go

fix selector help msg stylp
old:
```bash
-l, --selector stringArray            Only run using the releases that match labels. Labels can take the form of foo=bar or foo!=bar.
A release must match all labels in a group in order to be used. Multiple groups can be specified at once.
--selector tier=frontend,tier!=proxy --selector tier=backend. Will match all frontend, non-proxy releases AND all backend releases.
The name of a release can be used as a label. --selector name=myrelease
```
new:
```bash
-l, --selector stringArray            Only run using the releases that match labels. Labels can take the form of foo=bar or foo!=bar. 
A release must match all labels in a group in order to be used. Multiple groups can be specified at once.
"--selector …
```

fixed: selector help msg style

---

.github/workflows/ci.yaml
pkg/helmexec/exec.go
pkg/helmexec/exec_test.go
test/integration/run.sh
test/plugins/secrets/3.15.0/helm-secrets/plugin.yaml
test/plugins/secrets/4.0.0/helm-secrets/plugin.yaml

Helm-secrets has been released to v4.0.0 and the secret view command has been deprecated.
[Helm-secrets change log](https://github.com/jkroepke/helm-secrets/blob/v4.0.0/CHANGELOG.md), Helm secret view command. The helm secret decrypt command is a drop-in replacement.

Support helm-secrets v4.0.0

---

cmd/root.go
go.mod

remove flags.Parse in cobra
flags. Parse refers to the code of the helm, but I found that some parameter parsing exceptions would occur, so I removed this logic
```bash
[root@devops helmfile]# go run main.go template --args "-s templates/deployment.yaml"
environment will be: mplates/deployment.yaml [it's error]
args will be: -s templates/deployment.yaml
```
fixed: https://github.com/helmfile/helmfile/issues/299

remove flags.Parse in cobra

---

pkg/app/app.go
pkg/app/app_diff_test.go
pkg/app/testdata/app_diff_test/show_diff_on_changed_selected_release
pkg/app/testdata/app_diff_test/shows_no_diff_on_already_uninstalled_selected_release
pkg/app/testdata/app_diff_test_1/delete_foo_and_bar_when_bar_needs_foo
pkg/app/testdata/app_diff_test_1/delete_foo_and_bar_when_foo_needs_bar
pkg/app/testdata/app_diff_test_2/delete_foo_and_bar_when_bar_needs_foo
pkg/app/testdata/app_diff_test_2/delete_foo_and_bar_when_foo_needs_bar

Fix not to ignore diff selector when it matched nothing

---

README.md

Fix old link to the helmfile doc site.

docs: fix best pratices guide link

---

docs/index.md
pkg/state/state.go
pkg/state/state_test.go

Most shells do not support hyphens in environment variables.
However, there are cases where you may want to include hyphens in the repository name.
Therefore, I have included a process in `gatherOCIUsernamePassword` to replace hyphens with underbar.
Signed-off-by: mugioka <okamugi0722@gmail.com>

imprv: convert hyphen included in repo name to underbar with gatherOCIUsernamePassword.

---

pkg/app/app_test.go
pkg/app/mocks_test.go
pkg/app/testdata/testapply/helm2_upgrade_when_tns1/foo_needs_tns2/bar/log
pkg/app/testdata/testapply/install/log
pkg/app/testdata/testapply/upgrade_when_bar_needs_foo,_with_ns_override/log
pkg/app/testdata/testapply/upgrade_when_bar_needs_foo/log
pkg/app/testdata/testapply/upgrade_when_foo_needs_bar,_with_ns_override/log
pkg/app/testdata/testapply/upgrade_when_foo_needs_bar/log
pkg/app/testdata/testapply/upgrade_when_ns1/foo_needs_ns2/bar/log
pkg/app/testdata/testapply/upgrade_when_ns2/bar_needs_ns1/foo/log
pkg/app/testdata/testapply_2/apply_release_with_preapply_hook/log
pkg/exectest/helm.go
pkg/helmexec/exec.go
pkg/helmexec/exec_test.go
pkg/helmexec/helmexec.go
pkg/state/state.go
pkg/state/state_test.go

Test:
```console
$ helm fetch https://github.com/jenkinsci/helm-charts/releases/download/jenkins-4.2.6/jenkins-4.2.6.tgz
$ mv -f jenkins-4.2.6.tgz jenkins.tgz
$ helmfile sync
UPDATED RELEASES:
NAME      CHART           VERSION
jenkins   ./jenkins.tgz          
$ ./helmfile sync
UPDATED RELEASES:
NAME      CHART           VERSION
jenkins   ./jenkins.tgz     4.2.6
```

Use helm show chart to identify chart version

---

docs/index.md
pkg/state/state.go
pkg/state/state_test.go

Make possible to retrieve username/password from the environment for Helm repositories, like it is done for OCI registries.
Related to https://github.com/roboll/helmfile/pull/1629

feat: retrieve repository's username/password from environment

---

cmd/apply.go
cmd/diff.go
cmd/sync.go
pkg/app/app.go
pkg/app/app_apply_hooks_test.go
pkg/app/app_apply_nokubectx_test.go
pkg/app/app_apply_test.go
pkg/app/app_diff_test.go
pkg/app/app_test.go
pkg/app/config.go
pkg/app/diff_nokubectx_test.go
pkg/app/diff_test.go
pkg/config/apply.go
pkg/config/diff.go
pkg/config/sync.go
pkg/helmexec/exec.go
pkg/helmexec/exec_test.go
pkg/state/state.go
pkg/state/state_test.go

fix: https://github.com/helmfile/helmfile/issues/221
add reuse-values args for diff apply and sync

feat: add reuse-values args for diff apply and sync

---

pkg/helmexec/exec.go
pkg/helmexec/exec_test.go

Discussion: https://github.com/helmfile/helmfile/discussions/426
---
This improves the `helmfile sync` performance.
From the code: `BuildDeps` is used only by `runHelmDepBuilds`, which only is used by `PrepareCharts` which is finally only used by `withPreparedCharts`.
`withPreparedCharts` already does `SyncReposOnce` which means we do not have to refresh the local repository cache on each chart build.
This is only supported in Helm v3.
This seems to be mostly affecting helmfiles which have a lot of releases and those release charts use sub dependencies.
I saw significant performance improvements for a helmfile with 45 releases, 2 repositories, and most of the charts also had their own dependencies. Results:
Before the patch:
* real  9m10.565s
* real  9m38.335s
* real  9m14.941s
* real …

Add `--skip-refresh` flag to the build command

---

Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu

To avoid wget output / progress. and uniformise usage between curl / wget

use curl instead of wget & update helm to 3.10.1

---

pkg/app/app.go
pkg/state/state.go
pkg/state/state_test.go
test/e2e/template/helmfile/testdata/snapshot/issue_2098_release_template_needs/output.yaml

related to #460
basepath is "." in each subhelmfile state. so the previous PR could not get the full path to subhelmfile.
This PR change the `# Source: <subhelmfile>` in the build command, so no risk.

use fs.Getwd() to get working dir for sub helmfile

---

pkg/app/app_apply_nokubectx_test.go
pkg/app/snapshot_test.go

Use the new runWithLogCapture helper instead of the long boilerplate to capture the log for snapshot testing.
We have a bunch of same boilerplates over many test sources. I'll convert those to use the new helper in follow-up PRs.

Introduce a new test helper for easier log snapshot testing

---

.github/workflows/ci.yaml
Makefile

I have used `make fmt` for formatting code before submitting a pull request. It turned out not to work in some cases where you added a new import because the default go-fmt does not organize imports as the golangci-lint and gci expect.
This fixes that, by adding a gci command to the `make fmt` target.
Please note that this does not cover installing gci. If you need it, please submit another pull request to add something like a `make install-gci` and make the `make fmt` dependent on that target, so that one can get automatic gci installation when running `make fmt` for the first time.

Enhance `make fmt` to cover running gci for golangci-lint compat

---

cmd/apply.go
cmd/diff.go
cmd/sync.go
docs/index.md
pkg/state/state.go
pkg/state/state_test.go

adds option to declare `--reuse-values` control mode via `.helmDefaults.reuseValues` in `helmfile.yaml`

declare "reuse values" control mode in helmDefaults

---

cmd/root.go
docs/index.md
docs/paths.md
pkg/filesystem/fs.go
pkg/filesystem/fs_test.go
test/integration/test-cases/happypath.sh

fix: #505 
example: 
```
cat examples/helmfile.yaml | helmfile -f - template
```

Allow helmfile statefile to passed by stdin

---

docs/index.md
pkg/envvar/const.go
pkg/helmexec/runner.go
pkg/remote/remote.go
pkg/state/create.go
test/e2e/template/helmfile/snapshot_test.go
test/e2e/template/helmfile/testdata/snapshot/pr_560/config.yaml
test/e2e/template/helmfile/testdata/snapshot/pr_560/input.yaml
test/e2e/template/helmfile/testdata/snapshot/pr_560/output.yaml

Before this PR, only `values` can be used with go-getter and not `secrets`. The PR implement `remote FS` for secrets as well to maintain the consistency.
```
#{{ $configRepo := "git::https://example.xxx/yyy/zzz.git" }}
environments:
'{{ .Environment.Name }}':
values:
#{{- if .Environment.Values }}
- {{- .Environment.Values | toYaml | nindent 6 }}
#{{- else}}
- ../envs/_default.yaml
- ../envs/{{ $env }}.yaml
- '{{ $configRepo }}@/{{ $env }}.yaml?ref={{ env "CONFIG_REPO_REF" | default "main" }}'
#{{- end }}
secrets:
#{{- not if .Environment.Values }}
- ../envs/{{ $env }}.secrets.yaml
- '{{ $configRepo }}@/{{ $env }}.secrets.yaml?ref={{ env "CONFIG_REPO_REF" | default "main" }}'
#{{- end }}
```
Local test:
we can see: `skipping missing values file matching` and `skipping missing secrets file …

Use go-getter with secrets as well

---

docs/index.md
pkg/app/app.go
pkg/app/testdata/testapply/noop/log
pkg/app/testdata/testapply_hooks/hooks_for_no-diff_release/log

Fix  preapply hooks are not called on no diff when run apply subcommand

---

Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu

This PR is the late follow-up for https://github.com/helmfile/helmfile/discussions/296
As already described there, other users than root currently cannot use e.g. the Helm plugins (without setting necessary environment variables) - only chmod'ing the /root dir for other users is not enough.

Allow running images with users other than root

---

pkg/app/app_test.go
pkg/app/mocks_test.go
pkg/exectest/helm.go
pkg/helmexec/exec.go
pkg/helmexec/exec_test.go
pkg/helmexec/helmexec.go
pkg/state/state.go
pkg/state/util.go
test/e2e/template/helmfile/snapshot_test.go
test/e2e/template/helmfile/testdata/snapshot/chart_need/output.yaml
test/e2e/template/helmfile/testdata/snapshot/chart_need_enable_live_output/config.yaml
test/e2e/template/helmfile/testdata/snapshot/chart_need_enable_live_output/input.yaml
test/e2e/template/helmfile/testdata/snapshot/chart_need_enable_live_output/output.yaml
test/e2e/template/helmfile/testdata/snapshot/oci_need/output.yaml
test/e2e/template/helmfile/testdata/snapshot/pr_560/output.yaml
test/e2e/template/helmfile/testdata/snapshot/templated_lockfile/config.yaml
test/e2e/template/helmfile/testdata/snapshot/templated_lockfile/input.yaml
test/e2e/template/helmfile/testdata/snapshot/templated_lockfile/output.yaml

All the dependencies get correctly installed when dealing with remote charts.
If there's a local chart that depends on remote dependencies then those don't get automatically installed. See #526. They end up with this error:
```
Error: no cached repository for helm-manager-b6cf96b91af4f01317d185adfbe32610179e5246214be9646a52cb0b86032272 found. (try 'helm repo update'): open /root/.cache/helm/repository/helm-manager-b6cf96b91af4f01317d185adfbe32610179e5246214be9646a52cb0b86032272-index.yaml: no such file or directory
```
One workaround for that would be to add the repositories from the local charts. Something like this:
```
cd local-chart/ && helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
```
This …

Avoid --skip-refresh on local charts

---

pkg/helmexec/exec.go
pkg/state/helmx.go
pkg/state/state.go

clean: optimize post-render code

clean: optimize post-render code

---

.github/workflows/publish_v1_binaries.yml
.goreleaser.yml
Makefile
cmd/root.go
pkg/envvar/const.go
pkg/runtime/runtime.go

We add a new "V1 mode" to Helmfile so that you can seemlessly upgrade Helmfile from the current v0.x to the upcoming v1.0.
The idea is that we build both v0 and v1 binaries from the same tagged commit within the main branch, with different defaults for the "V1 mode"- the V1 mode is disabled by default for v0.x binaries, while it is enabled by default for v1.x binaries.
The V1 mode can be overrode at runtime via envvar. That is, even after upgrading the binary to v1, you will not see any backward-incompatible changes while you explicitly set an envvar, `HELMFILE_V1MODE=true`, at runtime.

feat: Helmfile V1 mode

---

pkg/state/release.go

Previously a values template rendering failure resulted in a cryptic error message like:
```
release templates in "input.yaml": failed executing templates in release "input.yaml"."foo1": failed executing template expressions in release "foo1".values[0] = "[98 97 115 101 76 97 98 101 108 58 32 34 123 123 32 103 101 116 32 46 82 101 108 101 97 115 101 46 76 97 98 101 108 115 32 92 34 98 97 115 101 92 34 32 92 34 78 79 84 95 73 78 72 69 82 73 84 69 68 92 34 32 125 125 34 10]": template: stringTemplate:1: unexpected "\\" in operand
```
The issue was that the values template at the value position of the YAML dict was printed as a formatted byte array. We now print it as a standard string so that it is easily readable.

Fix cryptic message on values template render error

---

cmd/apply.go
cmd/diff.go
cmd/sync.go
docs/index.md
pkg/app/app.go
pkg/app/app_test.go
pkg/app/config.go
pkg/app/diff_test.go
pkg/config/apply.go
pkg/config/diff.go
pkg/config/sync.go
pkg/state/state.go
pkg/state/state_test.go

implemented `--reset-values` flag overriding `.helmDefaults.reuseValues=true`
as discussed: https://github.com/helmfile/helmfile/discussions/593

Reset values flag

---

pkg/remote/remote.go

The go-getter driver (named `Remote`) is used to implement remote values. I found some unused functions in its implementation. This commit removes those unused functions so that it becomes more maintainable.

Remove unused go-getter driver funcs

---

docs/index.md
pkg/state/create.go
pkg/state/environment.go
pkg/state/state.go
pkg/state/storage.go
pkg/state/storage_test.go

This enables you to specify missingFileHandlerConfig along with the existing missingFileHandler per release and per environment to fine-tune how the missing file handler works.
The first and the only supported setting is `ignoreMissingGitBranch,` which makes the handler treat Git command errors like `pathspec 'develop' did not match any file(s) known to git` as non-errors, so that missing branches are handled same as missing files.
Resolves #392

feat: Add missingFileHandlerConfig.ignoreMissingGitBranch

---

docs/proposals/towards-1.0.md
pkg/app/app.go

Helmfile used to load helmfile.yaml or charts.yaml by default. It seems like we intended to remove charts.yaml from the defaults in v1 so this commit adds a condition to let Helmfile load the default charts.yaml only in v0 mode.

Do not load the legacy default charts.yaml in v1

---

pkg/app/testdata/testreadfromyaml_rendertemplatelog/v0mode/log
pkg/app/testdata/testreadfromyaml_rendertemplatelog/v1mode/log
pkg/app/two_pass_renderer.go
pkg/app/two_pass_renderer_test.go

We are going to force users to separate environments and releases sections in every helmfile.yaml in the [Helmfile V1](https://github.com/helmfile/helmfile/blob/main/docs/proposals/towards-1.0.md).
The goal of separation was to make the helmfile.yaml rendering result be not dependent on the double-rendering and therefore we should be able to turn off the feature safely in V1.

Disable double-rendering in V1

---

docs/index.md

* This section have been introduced originally in [PR#226](https://github.com/roboll/helmfile/pull/226) which relates to [issue155](https://github.com/roboll/helmfile/issues/155)
* As we already have the `--skip-deps` option, there is no need to run `helmfile charts` which is deprecated.
Signed-off-by: toyamagu2021@gmail.com <toyamagu2021@gmail.com>

docs: Running helmfile withought an internet connection by --skip-deps option

---

go.mod
go.sum
pkg/yaml/yaml_test.go

I forked goccy/go-yaml to https://github.com/helmfile/go-yaml and added a commit https://github.com/helmfile/go-yaml/commit/259d2ed450aed2aa1d6f05139f99a8b01f87633a to let it produce YAML data compatible with other legacy YAML parsers that do not support YAML 1.2.
Ref https://github.com/helmfile/helmfile/discussions/656

Use goccy/go-yaml fork to not break dynamic values on helmfile v1

---

pkg/app/app_template_test.go
pkg/state/state.go
pkg/state/state_exec_tmpl.go
pkg/state/temp_test.go
test/e2e/template/helmfile/testdata/snapshot/release_template_inheritance/input.yaml

It's only 1 minor release since we introduced `inherit` via #435. Assuming not many folks are using this feature, let me break and complete it earlier so that we are fully prepared to Helmfile v1 without leaving any tech debt.
This enhances `inherit` to support multi-inheritance:
BEFORE:
```
releases:
- name: myapp
inherit:
template: foo
```
```
releases:
- name: myapp
<<: [*foo, *bar]
```
AFTER:
```
releases:
- name: myapp
inherit:
- template: foo
- template: bar
```
This enhancement should allow folks relying on the YAML 1.1's `<<: [*foo, *bar]` syntax to migrate to the new `inherit` feature before upgrading to Helmfile v1 (or the v0's v1 mode).
The merge-key yaml syntax is born to deprecate and is no longer present in YAML 1.2.
Helmfile v1 is going to support YAML 1.2 only so we need …

breaking: Fix the inherit feature to support multi-inheritance

---

pkg/policy/checker.go

Currently, both v0 and v1 warns any usage of environments with releases within the same helmfile part.
It should rather be an error for v1, as proposed in https://github.com/helmfile/helmfile/blob/main/docs/proposals/towards-1.0.md#forbid-the-use-of-environments-and-releases-within-a-single-helmfileyaml-part.
Follow-up for #592

fix: Make the forbid-env-with-releases policy strict on v1

---

docs/proposals/towards-1.0.md

I think we never implemented support for .tpl suffixed helmfile.yaml.

Remove references to .tpl from v1 proposal

---

cmd/repos.go
docs/index.md

I do not change any logic of helmfile and only fix help message of `helmfile repos` command.
The help message was unclear, so I rewrote it as follows.
```
before: 
repos        Repos releases defined in state file
after:
repos        Add chart repositories defined in state file
```
Help message of `helm repo add` command, "add a chart repository" is used as a reference.

fix: repos command help message

---

go.mod
pkg/state/chart_dependency.go

go-version still exists in indirect because go-getter depends on it.

Use Masterminds/semver/v3 instead of hashicorp/go-version

---

pkg/app/app.go
pkg/app/app_test.go
pkg/app/mocks_test.go
pkg/exectest/helm.go
pkg/helmexec/exec.go
pkg/helmexec/exec_test.go
pkg/helmexec/helmexec.go
pkg/state/helmx.go
pkg/state/state.go
pkg/state/state_test.go

clean: optimize postrenderer code
it makes more sense that move postrenderer to `diffopts` `syncopts` and `applyopsts`

clean: optimize postrenderer code

---

docs/index.md

Resolves #722 
We have agreed to modify the doc since it looks a better solution than deprecate the kubeVersion field in the helmfile.yaml file.

Documentation updated about kubeVersion field

---

Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu
Makefile

Fixes #816 by building the correct helmfile binary for each arch.
Makes use of automatic platform ARGs that BuildKit has https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope

Build correct arch for container image

---

Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu
Makefile

Actually fix #816 and followup on #817
I also abstracted out the TARGETOS (right now just linux) in case you ever want more target platforms.

Fix depedency binaries for arm64 builds

---

pkg/state/state.go
pkg/state/state_test.go

The code requires `foo.enabled` condition pattern but didn't check the latter part.

fix: more stringent condition checking

---

cmd/root.go
docs/index.md
pkg/app/app.go
pkg/app/config.go
pkg/config/global.go
pkg/helmexec/exit_error.go
pkg/helmexec/exit_error_test.go
pkg/helmexec/runner.go
pkg/helmexec/runner_test.go
pkg/tmpl/context_funcs.go

Fixes #886 
Add --strip-args-values-on-exit-error=true to the helmfile CLI would change the output on a error from:
```
PATH:
/usr/local/bin/helm
ARGS:
0: helm (4 bytes)
1: upgrade (7 bytes)
2: --install (9 bytes)
3: value (5 bytes)
4: /var/folders/cs/zz5gz_v567v7y00jpvc5v16h0000gn/T/helmfile1974210836/value/values/1.0.4/values (93 bytes)
5: --version (9 bytes)
6: 1.0.4 (5 bytes)
7: --create-namespace (18 bytes)
8: --set (5 bytes)
9: a=v (3 bytes)
10: --set (5 bytes)
11: a=b (3 bytes)
12: --reset-values (14 bytes)
13: --history-max (13 bytes)
14: 10 (2 bytes)
ERROR:
exit status 1
EXIT STATUS
1
```
to
```
PATH:
/usr/local/bin/helm
ARGS:
0: helm (4 bytes)
1: upgrade (7 bytes)
2: --install (9 bytes)
3: value (5 bytes)
4: /var/folders/cs/zz5gz_v567v7y00jpvc5v16h0000gn/T/helmfile3802986705/valu …
```

Feat: add --strip-args-values-on-exit-error

---

pkg/app/desired_state_file_loader.go
pkg/app/testdata/app_list_test/fail_on_unknown_environment
pkg/app/testdata/app_list_test/filters_releases_for_environment_used_in_multiple_files
pkg/app/testdata/app_list_test/filters_releases_for_environment_used_in_one_file_only
pkg/app/testdata/app_list_test/list_releases_matching_selector_and_environment
pkg/app/two_pass_renderer.go
pkg/state/create.go
pkg/state/create_test.go
pkg/testhelper/require_log.go

This fixes helmfile to not fail in cases like https://github.com/helmfile/helmfile/issues/807#issuecomment-1515287329.
I consider this a bug in our validation logic that it was too strict!
The first commit f9f4972a980f0820695833a48d9ede5c6a163900 is there for making it easy to update the test snapshots.
Ref https://github.com/helmfile/helmfile/issues/807

Stop failing on single helmfile part missing specified env

---

pkg/app/desired_state_file_loader.go
test/e2e/template/helmfile/testdata/snapshot/environment_missing_in_subhelmfile/config.yaml
test/e2e/template/helmfile/testdata/snapshot/environment_missing_in_subhelmfile/helmfiles/prod.yaml
test/e2e/template/helmfile/testdata/snapshot/environment_missing_in_subhelmfile/helmfiles/test.yaml
test/e2e/template/helmfile/testdata/snapshot/environment_missing_in_subhelmfile/input.yaml
test/e2e/template/helmfile/testdata/snapshot/environment_missing_in_subhelmfile/output.yaml
test/e2e/template/helmfile/testdata/snapshot/environment_missing_in_subhelmfile/test.yaml.gotmpl

In #885, Helmfile v0.155.0, we made the missing env detection happen "after all the helmfile parts in a helmfile.yaml(.gotmpl) are rendered and merged".
That was indeed incorrect and resulted in any helmfile template part after the part that defines the `environments` part potentially failing.
This fixes that, by moving the env check a bit earlier than before. It now defers the env check until it sees one or more `environments` in the accumulated helmfile config.
Fixes #913

Cancel rendering helmfile parts once the missing env is detected in the previous part

---

.github/stale.yml

- labels bug and wontfix don't go well together
- shutting down comments on bug issues is something intended?
- changing the stale label from wontfix to stale is less confusing. (wont)fix reminds of bugs. wontfix on e.g. questions and enhancements is kind of strange to me.
- plus... https://github.com/helmfile/helmfile/issues/893 (bug issue):
🤣

add bug to exempt labels on git stale.yml

---

pkg/app/app_list_test.go
pkg/app/desired_state_file_loader.go
pkg/app/testdata/app_list_test/default_environment_includes_all_releases
pkg/app/testdata/app_list_test/fail_on_unknown_environment
pkg/app/testdata/app_list_test/filters_releases_for_environment_used_in_multiple_files
pkg/app/testdata/app_list_test/filters_releases_for_environment_used_in_one_file_only
pkg/app/testdata/app_list_test/list_releases_matching_selector_and_environment
pkg/policy/checker.go
pkg/policy/checker_test.go
pkg/state/state.go
test/e2e/template/helmfile/testdata/snapshot/environments_releases_within_same_yaml_part/output.yaml

feat: add kindful tips for helmfile config order.
check `bases` `environments` `releases` key order. And show more friendly tips.

feat: add friendly tips for helmfile config order

---

cmd/apply.go
cmd/diff.go
pkg/app/app.go
pkg/app/app_test.go
pkg/app/config.go
pkg/app/diff_test.go
pkg/config/apply.go
pkg/config/diff.go
pkg/state/state.go

`--diff-args` is useful to disable the validation only on helm diff. Additionally command like `--suppress ServiceMonitor` are only supported by helm diff, but not on helm ls. `--diff-args` make even sense on `helmfile diff`
Use cases:
If we want to install new CRDs and CR on that cluster on a helm chart which already present, the helm diff command files. since the new API object is present.
I'm aware that validation: false resolves the problem, however this would also skip the validation for the helm upgrade command. But I'm looking for a way to skip the validation ONLY for helm-diff.
--args is not helmful here, this command like helm ls are also affected and they fail then.

Implement --diff-args

---

docs/index.md

The images tagged helm3-* [don't seem to exist now](https://github.com/helmfile/helmfile/pkgs/container/helmfile) and the [current Dockerfile sets `$HOME` to `/helm`](https://github.com/helmfile/helmfile/blob/e4184a48b40e01d32db6bd6753879d8a0b256613/Dockerfile#L24-L25) (rather than /root) so the mounts need to change for version 0.156.0.

Update docs for running as container

---

cmd/root.go
docs/index.md
go.mod
go.sum
pkg/app/app.go
pkg/app/config.go
pkg/app/desired_state_file_loader.go
pkg/config/global.go
pkg/state/create.go
pkg/state/create_test.go
pkg/state/state.go
test/e2e/template/helmfile/testdata/snapshot/issue_2098_release_template_needs/output.yaml

Following https://github.com/helmfile/chartify/pull/62.
- Added `--kustomize-binary` (`-k`) flag and `kustomizeBinary` config option to set a custom kustomize binary.

feat: add an option to set a custom kustomize binary

---

pkg/filesystem/fs.go
pkg/filesystem/fs_test.go

Make sure to evaluate symlinks when the path is not absolute and not
local. Otherwise just fall back to regular absolute paths.
Fixes #1013

Fix symlink behaviour

---

docs/index.md
pkg/app/app.go
pkg/app/run.go
pkg/argparser/args.go
pkg/argparser/args_test.go
pkg/state/state.go

This OSS always helps me. Thank you to all the maintainers.
In my use case, I want to keep `diffArgs` in `helmfile.yaml`. (Added in #959)
I think this is useful if you want to specify additional arguments to `helm-diff` only when using a specific `helmfile.yaml`.
(It is now possible to version control argument specifications for specific charts)
Please let me know if there is anything else I need to do to fix it.
---
For example,
```
$ ls -l helmfile.yaml 
-rw-r--r-- 1 tkhs tkhs 1567 Sep 13 00:03 helmfile.yaml
$ /home/runner/work/helmfile/helmfile/helmfile diff
Adding repo eks https://aws.github.io/eks-charts
"eks" has been added to your repositories
Comparing release=aws-load-balancer-controller, chart=eks/aws-load-balancer-controller
kube-system, aws-load-balancer-tls, Secret (v1) has …
```

Add diffArgs to helmDefaults

---

go.mod

fix https://github.com/helmfile/helmfile/security/dependabot/33  
https://github.com/orgs/community/discussions/65431

fix: security/dependabot/33

---

go.mod
go.sum
pkg/remote/remote.go
pkg/remote/remote_test.go

> fork #834
This adds support for s3:// http:// https:// and most other go-getter style urls by
Adding http downloader
Adding s3 downloader that authenticates with aws sdk shared credentials
Changing the parser to accept remote formats that do not include '::'
Removing validation that required go-getter urls to contain '@' which is not required by go-getter spec
Resolves https://github.com/helmfile/helmfile/issues/831

feat: support most remote urls

---

pkg/state/helmx.go
pkg/state/helmx_test.go
pkg/state/state.go

optimize flag logic about wait

optimize flag logic about wait

---

docs/index.md

remote Environment values support more protocols, such as s3, https, http
pr: #1061

doc: remote Environment values support more protocols

---

test/e2e/template/helmfile/snapshot_test.go
test/e2e/template/helmfile/testdata/snapshot/issue_2098_release_template_needs/output.yaml

One of the tests were not portable and would only work in GitHub Actions.
This makes such test more portable.

test: fix running tests locally

---

pkg/app/app.go

fix: args ignore in diff subcommand

---

.readthedocs.yaml

The [readthedocs build](https://readthedocs.org/projects/helmfile/builds/) is failing due to a missing required `build.os`
```
Error
Problem in your project's configuration. Invalid configuration option "build.os": build not found
```

Fix failing docs build

---

USERS.md

Add [BlueLabs](https://bluelabs.eu/) to the list of `Helmfile` users. We have been using `Helmfile` since early 2021 to perform deployments to all our environments, including production. In early 2023 we started using it together with GitHub Actions to fully automate our deployments.

chore: add bluelabs to list of helmfile users

---

pkg/state/state.go
test/e2e/template/helmfile/testdata/snapshot/issue_1229_template_strategic_merge_with_lockfile/config.yaml
test/e2e/template/helmfile/testdata/snapshot/issue_1229_template_strategic_merge_with_lockfile/input.yaml
test/e2e/template/helmfile/testdata/snapshot/issue_1229_template_strategic_merge_with_lockfile/output.yaml
test/e2e/template/helmfile/testdata/snapshot/issue_1229_template_strategic_merge_with_lockfile/test-lock-file

Change ensures that dependencies are resolved in state.go prior to creating releases.
That way releases has proper version when helmfile.lock is present.

feat: respect helmfile.lock with ad-hoc kustimzation

---

pkg/state/state.go
test/integration/test-cases/happypath/input/environment.values.yaml
test/integration/test-cases/happypath/input/happypath.yaml

Prevent following things from
- using any unnecessary computing resources for disabled charts
- throwing any error from wrong configurations for disabled charts
PrepareCharts does not filter any releases whose condition is disabled with no selectors, so it use unnecessary computing resources

fix: prevent preparing chart for disabled releases

---

pkg/app/app.go
pkg/config/global.go
pkg/config/global_test.go
pkg/envvar/const.go

https://github.com/helmfile/helmfile/discussions/1254

add support for HELMFILE_FILE_PATH envvar to set -f 

---

pkg/policy/checker.go

At the moment the error message thrown when keys are in the wrong order provides the reverse error message to which it should be giving. This PR simply switches the format inputs of the provided error message (no unit tests affected). This gave me a few headaches until I worked through the logic of the code manually and noticed the bug in the error message 😄 
Simplified Helmfile example:
```yaml
releases: [...]
bases: [...]
```
Current error message provided when running a Helmfile command, e.g. `helmfile diff`:
```
in ./helmfile.yaml: top-level config key releases must be defined before bases in pre-install.yaml.gotmpl
```

fix checker error message

---

pkg/app/app.go
pkg/app/run.go
test/integration/run.sh
test/integration/test-cases/deps-mr-1011.sh
test/integration/test-cases/deps-mr-1011/input/helmfile.yaml

Hello!
with the following helmfile:
```yaml
releases:
- chart: rook-release/rook-ceph
name: rook-ceph
namespace: rook-ceph
values: ...
```
running `helmfile deps`  is OK, but with `dependencies` :
```yaml
releases:
- chart: rook-release/rook-ceph
name: rook-ceph
namespace: rook-ceph
dependencies:
- chart: jouve/extra
version: x
values: ...
```
`helmfile deps`  fails with the following error:
```
Updating dependency /tmp/chartify3667831028/rook-ceph/rook-ceph/rook-ceph
in ./helmfile.yaml: command "/usr/sbin/helm" exited with non-zero status:
PATH:
/usr/sbin/helm
ARGS:
0: helm (4 bytes)
1: dependency (10 bytes)
2: update (6 bytes)
3: /tmp/chartify3667831028/rook-ceph/rook-ceph/rook-ceph (53 bytes)
ERROR:
exit status 1
EXIT STATUS
1
STDERR:
Error: directory …
```

run deps without chart preparation

---

pkg/app/init.go

Fixes: #1350 
* #1350
Here's how it looks now:
* Install 
```sh
$ go run ./ init
The helm plugin "secrets" is not installed, do you want to install it? [y/n]: y
Install helm plugin secrets
Installed plugin: secrets
helmfile initialization completed!
```
* Upgrade
```sh
$ helm plugin  uninstall secrets
Uninstalled plugin: secrets
$ helm plugin install https://github.com/jkroepke/helm-secrets --version v4.0.0
Installed plugin: secrets
```
```
$ go run ./ init
The helm plugin "secrets" version is too low, do you want to update it? [y/n]: y
Update helm plugin secrets
Updated plugin: secrets
helmfile initialization completed!
```

Make it clear that the plugin install prompt is a question

---

cmd/apply.go
cmd/sync.go
docs/index.md
pkg/app/app.go
pkg/app/app_test.go
pkg/app/config.go
pkg/config/apply.go
pkg/config/sync.go
pkg/state/state.go
pkg/state/state_test.go

Currently there is no option to add arguments to the `helm upgrade` command without adding them to `helm diff` too.
This PR aims to solve this problem.
My usecase:
I would like to add the `--labels` flag to all `helm upgrade` invocations.
If I use `--args`, the diff fails because the `--labels` flag is unknown for the diff command.

Add the SyncArgs option and --sync-args flag

---

cmd/root.go
pkg/app/app.go
pkg/app/app_test.go
pkg/app/config.go
pkg/app/init.go
pkg/config/global.go
pkg/helmexec/exec.go
pkg/helmexec/exec_test.go

Similar to Helm and kubectl, I propose we add a kubeconfig flag.
This makes it also easier to run multiple Helmfile instances (eg. as a go library) without messing with the environment variables.

Add `--kubeconfig` flag

---

pkg/state/state.go
pkg/state/state_test.go

At the moment a condition is only allowed to be 2 deep eg: `foo.enabled`. This is a bit unfortunate because sometimes I work on projects where I have more deeply nested environment values to provide better structure. At the moment I kinda need maintain a separate configuration structure at the top to be able to have the condition work. For example
```yaml
apps:
my_app:
enabled: true
support:
something:
enabled: true
my_app:
enabled: true
something:
enabled: true
```
I traced the initial implementation back to this PR: https://github.com/roboll/helmfile/pull/1190. The limit of 2 deep is already set at this point, although no reason for it is mentioned. The current implementation can definitely be improved so feedback is welcome. But I was thinking to get the conversation started over a PR …

Allow for conditions to have a deeper nested structure.

---

Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu

My argumentation for upgrading to kubectl v1.28 (and not v1.27, v1.29 or v1.30):
The [current oldest supported k8s version is v1.27](https://kubernetes.io/releases/), which will become EoL on June 28th 2024.
The [kubectl version skew policy](https://kubernetes.io/releases/version-skew-policy/#kubectl) is:
> kubectl is supported within one minor version (older or newer) of kube-apiserver.
This means kubectl v1.28 is supported on k8s clusters versions v1.27, v1.28 and v1.29.
Assuming most production k8s clusters do not yet run v1.29 or v1.30, picking the second to last version will fit most users: v1.28.
Ref: https://github.com/helmfile/helmfile/discussions/1510

chore: upgrade kubectl to v1.28.9

---

docs/advanced-features.md

Noticed this when looking at the docs

Fix typo and link for supported backends

---

cmd/root.go
pkg/config/global.go
pkg/helmexec/exec.go
test/integration/test-cases/diff-args.sh
test/integration/test-cases/diff-args/output/apply
test/integration/test-cases/diff-args/output/apply-live
test/integration/test-cases/diff-args/output/apply-live-stderr
test/integration/test-cases/diff-args/output/apply-stderr
test/integration/test-cases/diff-args/output/diff-live-stderr
test/integration/test-cases/diff-args/output/diff-stderr
test/integration/test-cases/skip-diff-output/output/diff-result
test/integration/test-cases/skip-diff-output/output/diff-result-live

My previous PR was auto-closed: https://github.com/helmfile/helmfile/pull/1386
This PR updates all helm invocations, so the output is written to stderr via the logger only.
Only when templating, we write directly to stdout.
This PR aims to improve the experience when using helmfile as a go library.

Use logger for helm output

---

pkg/state/release_filters_test.go

**TestLabelFilterMatchSuccessfulMatch:**
This test verifies that the Match method of `LabelFilter` correctly identifies a match when a release meets the specified positive label criteria & does not meet the negative label criteria.
**TestLabelFilterMatchWithNegativeLabels:**
This test is testing the Match method of `LabelFilter` when a release contains a label that matches the negative label criteria, ensuring it returns false.
**TestParseLabelsValidInput:**
This test validates the `ParseLabels` func behavior with valid input, ensuring it correctly parses and separates positive and negative labels.
**TestParseLabelsInvalidFormat:**
This test, will test the `ParseLabels` func's error handling when provided with malformed input.

chore: add tests for release filters

---

pkg/state/state.go

It is desirable to be able to specify a docker_config.json file containing auth information, so we can fetch charts from private OCI registries.
This change adds `registryConfig` as a Repository option, which is only used when the helm chart is pulled down from OCI registries by using helm's `--registry-config` flag.

feat: add support for OCI auth through registry-config flag

---

pkg/errors/errors.go

The updated **HandleExitCoder** function is better because it simplifies the `type assertion` and `error handling` by removing the redundant check for an empty error message, making the code more concise. It also eliminates the unnecessary `return` statement.
I re-ran the tests **errors_test.go** for regression testing and it passed

chore: remove unecessary check in HandleExitCoder function and streamline logic

---

pkg/state/state.go
pkg/state/state_test.go

fixes #928
Previously `--output-dir-template` was not used if the repository was OCI.
```yaml
repositories:
- name: karpenter
url: public.ecr.aws/karpenter
oci: true
- name: gatekeeper
url: https://open-policy-agent.github.io/gatekeeper/charts
releases:
- name: karpenter
chart: karpenter/karpenter
version: "0.37.0"
- name: gatekeeper
chart: gatekeeper/gatekeeper
```
```
helmfile fetch --output-dir charts --output-dir-template "{{ .OutputDir }}/"
```
```
charts
├── gatekeeper
│   ├── Chart.yaml
│   ├── README.md
│   ├── crds
│   │   ├── assign-customresourcedefinition.yaml
│   │   ├── assignimage-customresourcedefinition.yaml
│   │   ├── assignmetadata-customresourcedefinition.yaml
│   │   ├── config-customresourcedefinition.yaml
│   │   ├── …
```

fix(oci): use output-dir-template in path if specified

---

Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu

Update the versions of the helm plugins in the Dockerfile to the latest stable versions:
- helm-s3: v0.16.0 -> v0.16.2
This update ensures that the Docker image is using the most up-to-date versions of the helm plugins s3.

build(deps): helm-s3: v0.16.0 -> v0.16.2

---

pkg/policy/checker.go
pkg/policy/checker_test.go

**Updating TopKeys func:**
**Trimming Whitespace:** Using `strings.TrimSpace` to remove any leading or trailing whitespace from the line before processing it. We need to do this because we want any accidental leading or trailing spaces removed before processing the line.
**Skipping Empty Lines:** Skipping over any empty lines to avoid unnecessary processing. We need to do this so we can avoid adding any empty keys to the list
**Consistent String Matching:** Using MatchString instead of Match to directly work with strings, improving readability.
Using SplitN: strings.SplitN with n=2 ensures that only the first occurrence of : is used to split the string, making it more efficient.
**Tests added:**
**Testing malformed lines with special characters:** This test scenario makes sure that lines …

chore: enhance TopKeys function & adding test cases for malformed lines scenario in TopKeys func 

---

docs/templating_funcs.md
pkg/tmpl/context_funcs.go

Resolves #1656
It creates an `isDir` template function, which can be use like:
```
{{- if isDir "./subdirectory" }}
do whatever you want to
{{- end }}
```

feat: add isDir template function

---

docs/index.md
pkg/state/state.go
pkg/state/state_test.go
pkg/state/temp_test.go

accomplished by:
- Adding PlainHttp attribute to RepositorySpec, HelmDefault, ReleaseSpec
- When set to true, pass `--plain-http` to helm commands
Tweaked https://github.com/helmfile/helmfile/pull/1228 by @hoangelos
Resolves https://github.com/helmfile/helmfile/discussions/1224

feat: adding ability for for charts to be pulled with plain HTTP

---

pkg/state/state.go
pkg/state/state_test.go

https://github.com/helmfile/helmfile/issues/1659
move verify to the `helm pull` stage.
todos:

fix verify stage for helmfile when use oci as chart

---

Dockerfile.ubuntu

The Ubuntu version 20.04 (LTS) of the Ubuntu-based container image is pretty outdated (even though still supported). With this change the version is updated to version 24.04 (also LTS), which got released in April this year and will be supported until April 2029. This will be useful to everyone who builds on top of the image with more up-to-date packages.

chore: Update Ubuntu image to LTS version 24.04

---

.github/workflows/ci.yaml
Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu
pkg/app/init.go

This pull request includes updates to the Helm version across multiple files to ensure consistency and compatibility. The changes primarily involve updating the Helm version from `v3.16.1` to `v3.16.2` and updating the corresponding SHA256 checksums.
* [`.github/workflows/ci.yaml`](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL74-R95): Updated Helm version from `v3.16.1` to `v3.16.2` in multiple sections to ensure the CI workflow uses the latest version.
* [`Dockerfile`](diffhunk://#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L33-R42): Changed Helm version to `v3.16.2` and updated SHA256 checksums for `linux/amd64` and `linux/arm64`.
* [`Dockerfile.debian-stable-slim`](diffhunk://#diff-ba602f969c43d8bdc4cbe0c2243476dfcc51f818d28f …

feat(helm-version): Update helm version to v3.16.2

---

pkg/state/state.go
pkg/state/state_test.go

I believe this is better because:
- When in `sync` operation, the summary now distinguishes between failed releases and failed to delete releases, which is more informative.
- When in `destroy` operation, the summary of failed releases no longer includes information that are only relevant to `sync` operation, like `CHART` name and version, which is not even required for the `helm delete` command.
Previous:
```console
$ helmfile destroy
DELETED RELEASES:
NAME    NAMESPACE   DURATION
raw-1                     0s
FAILED RELEASES:
NAME    NAMESPACE   CHART                                                                          VERSION   DURATION
raw-2               https://github.com/dysnix/charts/releases/download/raw-v0.3.2/raw-v0.3.2.tgz                   0s
```
After:
```console
$ …
```

feat: improve summary for releases failed to delete

---

pkg/app/app.go
pkg/state/state.go

--skip-refresh right now disables adding new repos, but in addition it should pass down to helm deps update to not refresh the actual values

[feature] --skip-refresh to pass through to deps

---

cmd/apply.go
cmd/sync.go
go.mod
go.sum

This pull request introduces a new flag to the `apply` and `sync` commands and removes an unused dependency from the `go.mod` file. The most important changes are summarized below:
* [`cmd/apply.go`](diffhunk://#diff-a08f2011636c2b27ac4df1809b3bf95ee8aa9a6de2050807d33ddfb65fb69f6fR64): Added the `--hide-notes` flag to the `apply` command to allow users to add the `--hide-notes` flag to Helm.
* [`cmd/sync.go`](diffhunk://#diff-6f5f9ca9ac82cbfb03857438b7f2b2373c6ddf3db19f1f68e7074242baebaadcR44): Added the `--hide-notes` flag to the `sync` command to allow users to add the `--hide-notes` flag to Helm.
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L201): Removed the unused `github.com/ghodss/yaml` dependency.

feat: add 'hide-notes' flag to helm in sync and apply commands

---

pkg/helmexec/exec.go

Reset extra args before running 'dependency build'

---

README.md

Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Helmfile Guru](https://gurubase.io/g/helmfile) to Gurubase. Helmfile Guru uses the data from this repo and data from the [docs](https://helmfile.readthedocs.io/en/latest/) to answer questions by leveraging the LLM.
In this PR, I showcased the "Helmfile Guru", which highlights that Helmfile now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution. …

Introducing Helmfile Guru on Gurubase.io

---

pkg/maputil/maputil.go
pkg/maputil/maputil_test.go

recently in our project, I faced a hidden issue where empty values from a yaml overwrites the whole key
for example in the base.yaml, we have : 
```yaml
key_1:
a: "a"
b:
b_1: "b_1"
b_2: "b_2"
key_2:
xxx: "something"
```
and another yaml to overwrite the base one:
```yaml
key_1:   \# merely a placeholder
key_2:
xxx: "something else"
```
then the result would be:
```yaml
key_1:
key_2:
xxx: "something else"
```
The `key_1` field is overwritten by the empty value. I figure it's a better idea not to overwrite with an nil value in this case.

fix(maputil): prevent nil value overwrite

---

test/advanced/helmfile.yaml

It fixes the error when trying the helmfile.
Error: repo "https://kubernetes-charts-incubator.storage.googleapis.com" is no longer available; try "https://charts.helm.sh/incubator" instead

fix: this url doesn't work anymore

---

test/e2e/template/helmfile/testdata/snapshot/issue_498_template_go_getter_with_selector/input.yaml

This pull request includes a change to the `input.yaml` file to update the URL of a chart repository.
* [`test/e2e/template/helmfile/testdata/snapshot/issue_498_template_go_getter_with_selector/input.yaml`](diffhunk://#diff-9d4beeb294b3e6678fef6dc5f84a5d776404b2e83c02a811ec68908df6e11406L7-R7): Changed the chart URL from `https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master` to `https://github.com/jenkins-x/acme.git@charts/acme?ref=main`.
https://github.com/jenkins-x/acme.git@charts/acme?ref=main had gone.

fix: update acme chart URL in input.yaml

---

README-zh_CN.md
README.md
docs/index.md

Due to [the sunset of Deta Space](https://deta.space/sunset), `deta.dev` must be replaced by `egpl.dev`.
ref: https://github.com/eggplants/ghcr-badge/issues/187

Revive dead badge links

---

README-zh_CN.md

This pull request includes a small change to the `README-zh_CN.md` file. The change adds a new badge for Gurubase to the list of badges.
* [`README-zh_CN.md`](diffhunk://#diff-099beda0196f3588b806c1d7ace4d054b6a1caf09bfede3b0c1a9ac7cfb74473R19): Added a new badge for Gurubase to the list of badges.

docs: Add Gurubase badge to README-zh_CN

---

docs/index.md
pkg/config/global.go
pkg/envvar/const.go

This PR adds the `HELMFILE_INTERACTIVE` environment variable to enable the interactive mode.
Anything other than `true` will disable the interactive mode. The precedence has the `--interactive` flag.
Example usage: `HELMFILE_INTERACTIVE=true helmfile apply`. It is equal to `helmfile apply --interactive`.
---
This is a small, transparent change. It doesn't impact other functionalities.
However, it will be very handy since there are some situations when using an alias `alias hi='helmfile --interactive'` isn't possible. For example, [Direnv](https://github.com/direnv/direnv?tab=readme-ov-file#faq) doesn't support aliases.

feat: add HELMFILE_INTERACTIVE env var to enable interactive mode

---

pkg/filesystem/fs_test.go

This pull request includes several improvements and refactoring changes to the test cases in the `pkg/filesystem/fs_test.go` file. The main focus is on enhancing the structure and readability of the test cases by using table-driven tests and the `assert` package for assertions.
Improvements to test structure and readability:
* [`pkg/filesystem/fs_test.go`](diffhunk://#diff-1d1d1b6189375ff7a21de9a5c1a961290e6e2ab68b86cf7c95bd3286344dca0cR10): Added the `assert` package to the imports for improved assertions.
* [`pkg/filesystem/fs_test.go`](diffhunk://#diff-1d1d1b6189375ff7a21de9a5c1a961290e6e2ab68b86cf7c95bd3286344dca0cL42-R184): Refactored the `TestFs_resolveSymlinks` function to use table-driven tests, improving readability and maintainability.
* …

chore: update with testify/assert assertion and table driven tests for fs.go

---

docs/remote-secrets.md

- Address changes to the URL of the google chart
- Address warning that helmfile generates about splitting environments and releases
Related to #1808

update example chart URL in remote-secrets doc

---

docs/index.md

This is a simple fix to the indention.

chore(doc): fix the indent of the selector usage sample yaml

---

docs/index.md
pkg/app/app_test.go
pkg/state/state.go
pkg/state/state_exec_tmpl.go
pkg/state/temp_test.go

This pull request introduces new functionality for handling `set-string` values in Helm releases and includes corresponding tests. The most important changes are as follows:
* **Addition of `SetStringValues` field**: A new field `SetStringValues` is added to the `ReleaseSpec` struct to support `set-string` values in Helm releases. (`pkg/state/state.go`)
* **Handling `set-string` flags**: Implemented the `setStringFlags` function to generate the `--set-string` flags for Helm, ensuring proper rendering of values and secrets. (`pkg/state/state.go`)
* **Incorporation in namespace and values flags**: Modified the `namespaceAndValuesFlags` function to include `set-string` flags if `SetStringValues` are present. (`pkg/state/state.go`)
* **New test function**: Added `testSetStringValuesTemplate` …

feat(state): add support for setString in ReleaseSpec and HelmState

---

pkg/state/state_test.go

This pull request includes a new test function to the `pkg/state/state_test.go` file. The new function, `TestHelmState_setStringFlags`, tests the `setStringFlags` method of the `HelmState` struct.
New test function:
* [`pkg/state/state_test.go`](diffhunk://#diff-e276c65aad47f6c58e4c8e8dd0192233e623108558fd69805f89743620b9e425R4206-R4265): Added `TestHelmState_setStringFlags` to test various scenarios for the `setStringFlags` method, including single value, multiple values, and rendered value error cases.

test(state): add TestHelmState_setStringFlags for setStringFlags method

---

.github/workflows/ci.yaml
Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu
pkg/app/init.go

This pull request includes updates to the Helm version across multiple files to ensure consistency and compatibility with the latest features and security patches. The most important changes include updating the Helm version in various configuration and Docker files, as well as updating the recommended Helm version in the application initialization file.
Version updates:
* [`.github/workflows/ci.yaml`](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL74-R95): Updated Helm version from `v3.16.3` to `v3.16.4`.
* [`Dockerfile`](diffhunk://#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L33-R42): Updated Helm version from `v3.16.3` to `v3.16.4` and updated corresponding SHA256 checksums.
* …

build: update Helm version to v3.16.4 in CI and Dockerfiles

---

Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu
pkg/app/init.go

This pull request includes updates to the `helm-diff` plugin version across multiple Dockerfiles and the initialization file. The primary goal is to upgrade the `helm-diff` plugin from version `v3.9.12` to `v3.9.13`.
Version updates:
* [`Dockerfile`](diffhunk://#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L97-R97): Updated `helm-diff` plugin version from `v3.9.12` to `v3.9.13`.
* [`Dockerfile.debian-stable-slim`](diffhunk://#diff-ba602f969c43d8bdc4cbe0c2243476dfcc51f818d28f079418302e94cf7e791aL102-R102): Updated `helm-diff` plugin version from `v3.9.12` to `v3.9.13`.
* [`Dockerfile.ubuntu`](diffhunk://#diff-b4c6189f9184e61338a887d10410ec33e466f2fdba640cb632fab869dcb8b289L102-R102): Updated `helm-diff` plugin version from `v3.9.12` to `v3.9.13`.
* …

build: update helm-diff to v3.9.13 in Dockerfiles and init.go

---

go.mod
go.sum

https://ogma.in/understanding-and-mitigating-cve-2024-45338-golang-denial-of-service-vulnerability

CVE-2024-45338: updating golang.org/x/net: to version: v0.33.0

---

pkg/app/app_template_test.go
pkg/helmexec/exec.go
pkg/helmexec/exec_test.go
pkg/state/state.go
pkg/state/state_test.go

closes #1864
This pull request includes refactorings to ensure the `--devel` flag is correctly passed into the required `helm` and `helm diff` commands.
- [`pkg/helmexec/exec.go`](https://github.com/helmfile/helmfile/pull/1865/files#diff-cc23d827ce15a3ce002578cc0b18d846fd3614d59ac080c703bdd17881466795R522): No longer set the version from the chart name and allow it to be passed through as part of the additional flags. This ensures `--version` and `--devel` are never included together. If you read the helm CLI docs, `--version` disables the behaviour of `--devel`.

fix: ensure development versions of charts can be used across helmfile commands

---

pkg/app/app.go
pkg/state/state.go
test/integration/test-cases/issue-1749/input/helmfile.d/helmfile1.yaml.gotmpl
test/integration/test-cases/issue-1749/input/helmfile.d/helmfile2.yaml.gotmpl

When having multiple helmfiles in one helmfile.d folder and multiple of them having repositories defined, the errors mention in #1749 still existed.
Fixes #1749 (again)

Ensure 'helm repo add' is also not pollute on helmfile template

---

pkg/app/desired_state_file_loader.go
pkg/state/release.go
pkg/state/state_exec_tmpl_test.go

This commit is supposed to add template support to post renderer args. Also, to make it possible to template arguments that are added to helm defaults, during the load, I'm removing default post renderer args from the state and putting them to each release, unless custom args are defined for the release.
Why do I need it? 
I'm trying to implement some kind of audit log to the helmfile. The idea is pretty simple, I'm adding a configmap that contains an information that can be used to identify a person that has sync the release via helmfile. In the first implementation, I was using subcharts with some `.Release.Set` fields, added via templates, so I could just add a release like that
```yaml
templates:
apply-log:
dependencies:
- chart: ./charts/apply-log
version: '0.1.0'
alias: apply-log …
```

feat: execute templates against postRendererHooks

---

go.mod
go.sum

fixes: https://github.com/helmfile/helmfile/issues/1079
This pull request includes a minor update to the `go-yaml` dependency in the `go.mod` file. The change updates the version from `v1.15.20` to `v1.15.21`.
Dependency update:
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L11-R11): Updated `github.com/goccy/go-yaml` from `v1.15.20` to `v1.15.21`.

build: update go-yaml to v1.15.21

---

docs/index.md
pkg/app/app.go
pkg/app/config.go
pkg/config/apply.go
pkg/config/sync.go
pkg/config/template.go
pkg/state/state.go

This pull request introduces the `--skip-schema-validation` flag to various parts of the codebase, ensuring that schema validation can be skipped during Helm operations. The changes span multiple files and include both documentation updates and functional code modifications.
Key changes include:
* Added `skipSchemaValidation` flag to `helmDefaults` and `releases` sections in `docs/index.md`. [[1]](diffhunk://#diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6R196-R197) [[2]](diffhunk://#diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6R318-R319)
* Updated `pkg/app/app.go` to include `SkipSchemaValidation` in the `apply`, `sync`, and `template` functions. [[1]](diffhunk://#diff-63facfa8b028c9f397524787fac074737e5534ae2591640c1a029549ec3d7450R1444) …

docs: add skipSchemaValidation to index.md and update related structs

---

pkg/state/state.go

This pull request includes changes to the `pkg/state/state.go` file to improve the handling of Helm template flags. The most important changes involve the refactoring of variable initialization and the addition of a new flag for schema validation.
Improvements to Helm template flags handling:
* [`pkg/state/state.go`](diffhunk://#diff-7e4e87a1e777423a3d9a915e00fb78a9c4fc2f4c476863f60b67e89b9c635697L2827-R2844): Refactored the initialization of `postRenderer`, `kubeVersion`, and `skipSchemaValidation` variables to ensure they are properly set when `opt` is not nil. This change also includes the addition of the `skipSchemaValidation` flag.

refactor(state): optimize HelmState flags handling

---

docs/proposals/towards-1.0.md

This pull request includes updates to the documentation in `docs/proposals/towards-1.0.md` to reflect recent changes and deprecations in the project. The most important changes include the addition of new deprecations and alternative commands.
Documentation updates:
* Added a new section to list the removal of `helmfile charts` and `helmfile delete` subcommands, recommending the use of `helmfile destroy` and `helmfile sync` instead.
* Updated the table of contents to include the new section on the removal of `helmfile charts` and `helmfile delete` subcommands.

feat(docs): add proposal to remove charts and delete subcommands

---

.github/workflows/ci.yaml
Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu
go.mod
pkg/tmpl/context_funcs.go

This pull request includes updates to the CI workflow and Go module version.
Changes to CI workflow:
* Updated the `golangci-lint-action` version from `v1.61.0` to `v1.64.5` in `.github/workflows/ci.yaml`.
Changes to Go module:
* Updated the Go version from `1.23.1` to `1.24` in `go.mod`.

build: update golang version to 1.24 and golangci-lint to v1.64.5

---

docs/index.md

This pull request includes a minor change to the `docs/index.md` file. The change corrects a typo in the example of label selection by ensuring the label `tier=frontend` is correctly specified.
Documentation update:
* [`docs/index.md`](diffhunk://#diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6L767-R767): Corrected the label example from `tier=fronted` to `tier=frontend`.

docs(fix): correct typo in 'tier=fronted' to 'tier=frontend'

---

.github/workflows/releaser.yaml

This pull request adds a disk cleanup step to the release workflow to help free up space before running the release process.
* Workflow improvement:
* [`.github/workflows/releaser.yaml`](diffhunk://#diff-723fcb434a7bf0f56b6f4505b087ee476e1c11b0d4698eb9180a5928b1c7142cR33-R38): Added a new "cleanup disk" step that removes unused directories (`/usr/share/dotnet`, `/opt/ghc`, `/usr/local/share/boost`, and `$AGENT_TOOLSDIRECTORY`) to reduce disk usage prior to the release step.

cleanup disk in release ci
