.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/workflows/canary_images.yaml

Ref https://github.com/roboll/helmfile/issues/1824

Add an issue form for bug report

---

pkg/app/app.go
pkg/app/run.go
pkg/app/snapshot_test.go
pkg/helmexec/exec.go
pkg/remote/remote.go
pkg/state/chart_dependency.go
pkg/state/create_test.go
pkg/state/envvals_loader_test.go
pkg/state/state.go
pkg/state/state_gogetter_test.go
pkg/state/state_test.go
pkg/state/temp.go
pkg/tmpl/file_renderer.go
test/yamldiff/yamldiff.go

remove ioutil usage in all project

remove ioutil usage in all project

---

pkg/app/formatters_test.go
pkg/app/testdata/formatters/jsonoutput
pkg/app/testdata/formatters/tableoutput

add unittest for formatters.go

add unittest for formatters.go

---

pkg/app/app_test.go
pkg/app/formatters_test.go
pkg/testutil/testutil.go
pkg/testutil/testutil_test.go

mv captureStdout as public func

mv captureStdout as public func

---

pkg/app/load_opts_test.go

add unittest for load_opts.go

---

pkg/argparser/args.go
pkg/argparser/args_test.go

update args_test.go unittest
1. Optimize unit testing of GetArgs
2. add unittest for SetArgs

update args_test.go unittest

---

pkg/tmpl/context_funcs_test.go

1. add unittest for RequiredEnv func

add unittest for RequiredEnv func

---

go.mod
go.sum

Ref https://github.com/roboll/helmfile/issues/2106

Bump go-getter to 1.5.11

---

pkg/state/state.go

(fix) typo in state.go

---

pkg/helmexec/exec.go
pkg/helmexec/exec_test.go

The chart name can also be an URL that contains basic authentication information. This information are printed out by helmfile. This PR tries to redact this information.
```
$ cat <<EOT >> helmfile.yaml
releases:
- name: test
chart: https://foo:bar@charts.helm.sh/incubator/packages/druid-0.2.13.tgz
EOT
$ helmfile template
> Templating release=test, chart=https://foo:bar@charts.helm.sh/incubator/packages/druid-0.2.13.tgz
```
With this patch the output looks like:
```
> Templating release=test, chart=https://foo:xxxxx@charts.helm.sh/incubator/packages/druid-0.2.13.tgz
```` 
Moved from roboll/helmfile => roboll/helmfile#2132

Redact sensitive informations like password in chart url

---

pkg/app/constants_test.go
pkg/tmpl/expand_secret_ref_test.go

add unittest for constants.go

---

pkg/app/app_apply_nokubectx_test.go
pkg/app/app_apply_test.go
pkg/app/app_sync_test.go
pkg/app/app_test.go
pkg/app/destroy_nokubectx_test.go
pkg/app/destroy_test.go
pkg/app/diff_nokubectx_test.go
pkg/app/diff_test.go
pkg/state/create_test.go
pkg/state/state_exec_tmpl_test.go
pkg/state/state_test.go

fix go lint warn

---

Dockerfile
Dockerfile.debian
Dockerfile.ubuntu

I profit the PR to remove `pip` from debian-based images
Closes #41

feat: Add openssh-client to images

---

pkg/tmpl/context_funcs.go
pkg/tmpl/context_funcs_test.go

add unittest for Exec

---

pkg/helmexec/id_test.go

Add unittest for newExecutionID

Add unittest for newExecutionID

---

pkg/app/app_test.go
pkg/app/validate_config_test.go

add unittest for ValidateConfig

add unittest for ValidateConfig

---

pkg/helmexec/context_test.go

add unittest for context.go

---

pkg/app/errors_test.go

add unittest for error.go in pkg/app

add unittest for error.go in pkg/app

---

README.md
docs/templating_funcs.md

update doc for template func

---

README.md

Update to the latest release tag v0.143.4.

[#80] README, update release tag url

---

README.md
pkg/tmpl/context_funcs.go
pkg/tmpl/context_funcs_test.go

add execEnvs
TODO: in the next major version, remove this function
https://github.com/helmfile/helmfile/discussions/92

[feat] add execEnvs

---

.github/actions/setup-docker-environment/action.yaml
.github/workflows/images.yaml

build image on tag

---

docs/templating_funcs.md

update envExec docs

---

test/integration/issue.2118.yaml

fix intergration test for argo-cd form master to main branch
see: https://github.com/argoproj/argo-helm/pull/1295

fix intergration test for argo-cd form master to main branch

---

pkg/app/app.go
pkg/argparser/args.go

remove unused comments

---

Dockerfile
Dockerfile.debian
Dockerfile.ubuntu

Closes https://github.com/helmfile/helmfile/issues/121

Update Helm diff plugin to version 3.5.0 in Dockerfile

---

pkg/app/app.go
pkg/state/create.go

little code optimize

---

test/integration/issue.1867.yaml

fix ci issue

---

CODEOWNERS

I've asked a few times by @yxxhero if he deserves a seat as a maintainer of the Helmfile project.
Seeing the amount and the number of his recent contributions, and the nature of his contributions (add tests and fix bugs and CI issues, review PRs), I think he is in a relatively unique position compared to existing maintainers, and we can work better together!
@itscaro WDYT?

Add yxxhero as a maintainer

---

.github/ISSUE_TEMPLATE/bug.yml

It turned out we lack some important information that is necessary to make it a real bug without guesswork.
// My hope was that folks will create repositories containing the set of files to reproduce the exact issues. But those are often filled with just dummy values...

Enhance the bug report form

---

docs/templating_funcs.md

Fix documentation link and whitespaces.

Minor documentation fixes

---

cmd/repos.go
cmd/root.go
main.go

add repos subcommand to a file
see: https://github.com/helmfile/helmfile/discussions/82

Move repos subcommand to a dedicated source file

---

docs/proposals/towards-1.0.md

proposal: Drop --args in Helmfile 1.0

---

.github/workflows/images.yaml

docker build test on ci

---

pkg/app/app_lint_test.go
pkg/app/app_template_test.go
pkg/tmpl/text_renderer_test.go

add unittest for text_renderer.go

add unittest for text_renderer.go

---

.github/ISSUE_TEMPLATE/bug.yml

fix bug.yaml

---

pkg/app/app.go

fix within func issue

---

.github/workflows/images.yaml

Ref https://github.com/helmfile/helmfile/discussions/211

The image publishing workflow should trigger on version tags

---

README.md
docs/index.md

update readme about image repo and fix link error
docs/index.md and readme.md have path conflict;
Todo:
Signed-off-by: yxxhero aiopsclub@163.com

update readme about image repo and fix link error

---

pkg/helmexec/exec.go
pkg/helmexec/exec_test.go

Signed-off-by: Adam Gardner <adam.gardner@magicmemories.com>
Fixes #193

fix: use helm secrets view rather than helm secrets dec to decrypt

---

test/e2e/template/helmfile/snapshot_test.go

Signed-off-by: Tsubasa Nagasawa <toversus2357@gmail.com>
Fixe some nits I noticed while reviewing #239:
* `config.LocalDockerRegistry.Port` may be defaulted to zero

chore: clean up snapshot test

---

cmd/root.go

fix for #251
I applied the workaround described in https://github.com/kubernetes/minikube/pull/9614

correct --help cli arg regression

---

pkg/helmexec/exec_test.go

test: Add unit tests for ChartExport

test: Add unit tests for ChartExport

---

pkg/helmexec/exec_test.go

test: Add unit tests for ChartPull

test: Add unit tests for ChartPull

---

pkg/helmexec/exec.go
pkg/helmexec/exec_test.go

fix #244
Consider the following cases
```
1. registry:443/helm-charts
2. registry/helm-charts:latest
3. registry:443/helm-charts:latest
```

fix: OCI Url and Version parse error

---

docs/index.md

update doccs/index.md about CLI ref

update doccs/index.md about CLI ref

---

cmd/apply.go
cmd/build.go
cmd/cache.go
cmd/charts.go
cmd/delete.go
cmd/deps.go
cmd/destroy.go
cmd/diff.go
cmd/fetch.go
cmd/lint.go
cmd/list.go
cmd/repos.go
cmd/status.go
cmd/sync.go
cmd/template.go
cmd/test.go
cmd/version.go
cmd/write-values.go
pkg/config/lint.go

add flags about need for lint subcmd
Fixes: https://github.com/helmfile/helmfile/issues/247

Add flags about need for lint subcmd

---

go.mod
go.sum

fix go.mod

---

.github/workflows/images.yaml

fix tag miss in docker build

---

README.md

i do not change any logic of helmfile and only fix issue typo of readme

fix typo for readme.md

---

USERS.md

Signed-off-by: lemeurherve hlemeur@cloudbees.com
Update Jenkins Infrastructure helmfile repository location.

chore: update Jenkins's main helmfile repository in USERS

---

test/integration/issue.2118.yaml

Fixed: https://github.com/helmfile/helmfile/issues/318

fix ci error in issue.2118.yaml

---

README.md
USERS.md

[Add Users information in Readme.md](https://github.com/helmfile/helmfile/pull/317/commits/44669bb40aa193dcaf5ba079ecd8b05b61758cae)

Add Users information in Readme.md

---

docs/advanced-features.md

- A few typo fixes in [docs/advanced-features.md](https://github.com/helmfile/helmfile/compare/main...dreglad:helmfile-1:patch-1#diff-85ab93748a4d60eb555c792991e15e6439e46fcb96dc320dbb4844c4218b33f9)

Fix typos in docs

---

test/integration/issue.2118.yaml

use helmfile testdata

---

docs/index.md

update docs for CLI

---

.github/workflows/ci.yaml

fix github ci matrix config

---

cmd/root.go
go.mod
go.sum
main.go
pkg/errors/errors.go
pkg/errors/errors_test.go

fix incorrent exit code
fixed: #358 
1. remove all github.com/urfave/cli deps
2. fix cobra error
@mumoshu

Fix incorrent exit code issue introduced in v0.145.0

---

.github/workflows/ci.yaml

use latest helm in github ci

---

cmd/apply.go

Ref https://github.com/helmfile/helmfile/pull/279#discussion_r973675321

chore: Tidy up a local var scopinng for maintainability

---

cmd/apply.go
cmd/delete.go
cmd/destroy.go
cmd/root.go
cmd/sync.go
pkg/config/apply.go
pkg/config/delete.go
pkg/config/destroy.go
pkg/config/global.go
pkg/config/sync.go

move interactive option to global
fix: https://github.com/helmfile/helmfile/issues/366

move interactive option to global

---

cmd/root.go
docs/index.md

update CLI Ref

---

go.mod
go.sum

Resolves #229 and #308 via https://github.com/variantdev/chartify/pull/39 and https://github.com/variantdev/chartify/pull/38

Bump chartify to v0.11.0

---

pkg/state/util.go

fix path issue in windows
fix: https://github.com/helmfile/helmfile/issues/382

fix path issue in windows

---

cmd/build.go

Signed-off-by: Stoned Elipot <stoned.elipot@gmail.com>

fix: build command short description

---

cmd/build.go
cmd/charts.go
cmd/delete.go
cmd/deps.go
cmd/destroy.go
cmd/diff.go
cmd/fetch.go
cmd/lint.go
cmd/list.go
cmd/repos.go
cmd/status.go
cmd/sync.go
cmd/template.go
cmd/write-values.go

Optimize cmd pkg

---

.github/workflows/ci.yaml

Update ci.yaml and use helm 3.10.0

Update ci.yaml and use helm 3.10.0

---

go.mod
go.sum
pkg/app/app_test.go
pkg/app/load_opts.go
pkg/app/two_pass_renderer_test.go
pkg/environment/environment.go
pkg/maputil/yamlutil.go
pkg/maputil/yamlutil_test.go
pkg/remote/remote.go
pkg/state/chart_dependency.go
pkg/state/create.go
pkg/state/envvals_loader.go
pkg/state/release.go
pkg/state/state.go
pkg/state/state_exec_tmpl.go
pkg/tmpl/context_funcs.go
pkg/tmpl/context_funcs_test.go
test/e2e/template/helmfile/testdata/snapshot/issue_2098_release_template_needs/output.yaml
test/integration/issue.657.yaml
test/integration/run.sh
test/integration/yaml-features-golden/overwritten.yaml
test/yamldiff/yamldiff.go

fix: https://github.com/helmfile/helmfile/issues/394
bump: upgrade gopkg.in/yaml.v2 to gopkg.in/yaml.v3

bump: upgrade gopkg.in/yaml.v2 to gopkg.in/yaml.v3

---

docs/index.md

docs: update docs order

---

pkg/state/state.go
pkg/state/state_test.go

feat: add more clear error message and Environment info for template
fix: https://github.com/helmfile/helmfile/issues/409

feat: add more clear error message and Environment info for template

---

docs/templating_funcs.md

doc: update template funcs docs

doc: update template funcs docs

---

README.md

fix README.md users.md to USERS.md

fix README.md users.md to USERS.md

---

pkg/state/chart_dependency.go
pkg/state/chart_dependency_test.go

fix: helmfile deps issue with oci repo
fix: https://github.com/helmfile/helmfile/issues/405

fix: helmfile deps issue with oci repo

---

main.go
pkg/app/app.go

fix: child process not exit when recive term signal
issue: https://github.com/helmfile/helmfile/issues/416

fix: child process not exit when recive term signal

---

.github/workflows/ci.yaml
.github/workflows/lint.yaml
.github/workflows/publish_binaries.yaml
.github/workflows/test_binary_builds.yaml
Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu
go.mod

relates to https://github.com/Homebrew/homebrew-core/pull/112706

deps: build with go1.19

---

Makefile

fix helmfile version issue in docker image
fix: https://github.com/helmfile/helmfile/issues/425

fix helmfile version issue in docker image

---

cmd/deps.go
pkg/config/deps.go

fix: fix deps args

---

pkg/state/util.go

fix helmfile diff error in window platform
fix: https://github.com/helmfile/helmfile/issues/445

fix helmfile diff error in window platform

---

cmd/root.go
pkg/envvar/const.go

move HELMFILE_UPGRADE_NOTICE_DISABLED into envvar file

move HELMFILE_UPGRADE_NOTICE_DISABLED into envvar file

---

pkg/app/app.go
pkg/app/app_test.go
pkg/app/diff_test.go
test/integration/chart-needs-golden/diff
test/integration/chart-needs-golden/lint
test/integration/chart-needs-golden/template
test/integration/issue.455/azuredisk-csi-storageclass/azuredisk-csi-storageclass.yaml
test/integration/issue.455/helmfile.yaml
test/integration/run.sh
test/integration/test-cases/chart-needs.sh

fix: fix needs logic in chart stage

fix: needs logic in chart stage

---

cmd/apply.go
cmd/charts.go
cmd/delete.go
cmd/deps.go
cmd/destroy.go
cmd/diff.go
cmd/lint.go
cmd/repos.go
cmd/status.go
cmd/sync.go
cmd/template.go
cmd/test.go
pkg/config/apply.go
pkg/config/build.go
pkg/config/cache.go
pkg/config/charts.go
pkg/config/delete.go
pkg/config/deps.go
pkg/config/destroy.go
pkg/config/diff.go
pkg/config/fetch.go
pkg/config/global.go
pkg/config/lint.go
pkg/config/list.go
pkg/config/repos.go
pkg/config/status.go
pkg/config/sync.go
pkg/config/template.go
pkg/config/test.go
pkg/config/write-values.go

fix --debug flag

---

test/integration/issue.455/helmfile.yaml

fix chart needs test issue

---

pkg/argparser/args.go
pkg/argparser/args_test.go

fix: args parse issue

---

go.mod
go.sum
test/e2e/template/helmfile/testdata/snapshot/chart_need/output.yaml
test/e2e/template/helmfile/testdata/snapshot/chart_need_enable_live_output/output.yaml
test/e2e/template/helmfile/testdata/snapshot/oci_need/output.yaml

fix deps issues
fix: https://github.com/helmfile/helmfile/issues/430 https://github.com/helmfile/helmfile/issues/429

fix deps issues

---

test/e2e/template/helmfile/testdata/snapshot/issue_493_template_yaml_anchors_merge/config.yaml
test/e2e/template/helmfile/testdata/snapshot/issue_493_template_yaml_anchors_merge/input.yaml
test/e2e/template/helmfile/testdata/snapshot/issue_493_template_yaml_anchors_merge/output.yaml

test: add template anchors merge e2e test
related: https://github.com/helmfile/helmfile/issues/493

test: add template anchors merge e2e test

---

Makefile

feat: add go test total cover
```bash
github.com/helmfile/helmfile/pkg/tmpl/get_or_nil.go:84:			getOrNil					83.3%
github.com/helmfile/helmfile/pkg/tmpl/text_renderer.go:18:		NewTextRenderer					100.0%
github.com/helmfile/helmfile/pkg/tmpl/text_renderer.go:29:		RenderTemplateText				100.0%
total:									(statements)					63.2%
```

feat: add go test total cover

---

.github/workflows/ci.yaml
Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu
pkg/app/init.go

bump: helm to 3.10.2

---

pkg/app/app_apply_hooks_test.go
pkg/app/app_apply_nokubectx_test.go
pkg/app/snapshot_test.go

Along with the addition of the new arg to the helper for log level customization.

Use log capturing helper in TestApply_hooks

---

pkg/app/app_apply_test.go
pkg/app/app_diff_test.go
pkg/app/app_lint_test.go
pkg/app/app_list_test.go
pkg/app/app_sync_test.go
pkg/app/app_template_test.go
pkg/app/app_test.go
pkg/app/destroy_nokubectx_test.go
pkg/app/destroy_test.go
pkg/app/diff_nokubectx_test.go
pkg/app/diff_test.go

A few hundreds more LoC reduction 🎉

Use the new log capturing helper in all remaining tests

---

pkg/maputil/maputil.go
pkg/maputil/maputil_test.go

Fix getArray function copy error

---

test/integration/charts/httpbin/templates/deployment.yaml
test/integration/templates-golden/v2/httpbin/deployment.yaml
test/integration/templates-golden/v3/httpbin/deployment.yaml
test/integration/yaml-features-golden/overwritten.yaml

Remove redundant metadata fields from test samples

---

README.md

fix ghr badge

---

test/e2e/template/helmfile/testdata/snapshot/issue_473_oci_chart_url_fetch/output.yaml
test/e2e/template/helmfile/testdata/snapshot/oci_chart_pull/output.yaml
test/e2e/template/helmfile/testdata/snapshot/oci_need/output.yaml

fix unit test
@mumoshu 
BTW, I don't find the place where the helm installs in `tests` ci. Could you tell me?

fix unit test

---

docs/index.md

fix ghcr-badge in docs

---

.dockerignore
Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu

* use sha256sum -c to validate checksum
* use tar features to extract artifacts
* validate installed tools

rework dockerfiles

---

docs/index.md

Add documentation on go-getter cache

---

docs/index.md

Clarify postsync hooks docs

---

.github/workflows/lint.yaml
.golangci.yaml
pkg/app/init_test.go
pkg/helmexec/exec.go
pkg/helmexec/exec_test.go
pkg/state/chart_dependency.go
pkg/state/create.go
pkg/state/helmx.go
pkg/state/state.go
pkg/tmpl/text_renderer.go
test/diff-yamls/diff-yamls.go

optimize lint logic

---

pkg/state/state.go

use yaml v3 UnmarshalYAML

---

README.md
docs/index.md

add goreportcard

---

pkg/app/desired_state_file_loader.go

This is a successor to #440 rebuilt on top of #594 so that we can merge this while we are still at Hemlfile v0.x without worrying any backward-incompatibility. Much appreciation to @yxxhero for the original work!

Re: Strict helmfile.yaml file ext when rendered as template

---

pkg/app/desired_state_file_loader.go
pkg/environment/environment.go
pkg/environment/environment_test.go
pkg/state/create.go
pkg/state/envvals_loader.go
pkg/state/envvals_loader_test.go
pkg/state/testdata/values.6.yaml.gotmpl
test/e2e/template/helmfile/testdata/snapshot/environments_releases_within_same_yaml_part/config.yaml
test/e2e/template/helmfile/testdata/snapshot/environments_values_gotmpl_with_environment_name/config.yaml
test/e2e/template/helmfile/testdata/snapshot/environments_values_gotmpl_with_environment_name/input.yaml
test/e2e/template/helmfile/testdata/snapshot/environments_values_gotmpl_with_environment_name/output.yaml
test/e2e/template/helmfile/testdata/snapshot/environments_values_gotmpl_with_environment_name/test.yaml.gotmpl

fix env value lost in environment values

fix env value lost in environment values

---

docs/writing-helmfile.md
pkg/app/app_template_test.go
pkg/state/state.go
pkg/state/state_exec_tmpl.go
pkg/state/temp_test.go
test/e2e/template/helmfile/testdata/snapshot/pr_560/output.yaml
test/e2e/template/helmfile/testdata/snapshot/release_template_inheritance/config.yaml
test/e2e/template/helmfile/testdata/snapshot/release_template_inheritance/input.yaml
test/e2e/template/helmfile/testdata/snapshot/release_template_inheritance/output.yaml

Ref https://github.com/helmfile/helmfile/issues/435#issuecomment-1364749414

feat: `inherit` field for release template inheritance

---

pkg/tmpl/context_funcs_test.go

Enhance tpl func test

---

cmd/apply.go
cmd/charts.go
cmd/delete.go
cmd/root.go
pkg/app/app.go
pkg/app/app_test.go
pkg/app/config.go
pkg/app/constants.go
pkg/app/run.go
pkg/config/apply.go
pkg/config/charts.go
pkg/config/delete.go
pkg/state/create.go
pkg/state/create_test.go
pkg/state/state.go
pkg/state/state_test.go

mark deprecated args and cmd for v1.

feat: mark deprecated args and cmd for v1

---

pkg/state/state.go
test/integration/run.sh
test/integration/test-cases/kustomized-fetch.sh
test/integration/test-cases/kustomized-fetch/input/helmfile.yaml

fix fetch does not work with kustomized releases

---

.github/workflows/ci.yaml
.github/workflows/lint.yaml

Signed-off-by: Gaius <gaius.qi@gmail.com>

feat: add paths-ignore to ci.yaml and lint.yaml

---

pkg/app/desired_state_file_loader.go
pkg/state/state_exec_tmpl.go
test/e2e/template/helmfile/testdata/snapshot/release_template_inheritance/input.yaml

closes: https://github.com/helmfile/helmfile/issues/634

fix inherit chart empty check issue

---

cmd/delete.go
cmd/destroy.go
docs/index.md
pkg/app/app.go
pkg/app/config.go
pkg/app/destroy_test.go
pkg/config/delete.go
pkg/config/destroy.go
test/integration/test-cases/happypath.sh

add --skip-charts for destroy for disabling prepare charts
see: https://github.com/helmfile/helmfile/discussions/636

add --skip-charts for destroy for disable prepare charts

---

docs/proposals/towards-1.0.md

Fix a minor typo in the v1 proposal

---

test/integration/run.sh
test/integration/test-cases/chart-needs.sh
test/integration/test-cases/happypath.sh
test/integration/test-cases/postrender-diff.sh
test/integration/test-cases/regression.sh
test/integration/test-cases/secretssops.sh
test/integration/test-cases/yaml-overwrite.sh

remove helm v2 code in tests

---

pkg/app/init.go

use latest helm previous minor version for helmfile init

use latest helm previous minor version for helmfile init

---

pkg/app/app.go
pkg/app/testdata/app_list_test/default_environment_includes_all_releases
pkg/app/testdata/app_list_test/fail_on_unknown_environment
pkg/app/testdata/app_list_test/filters_releases_for_environment_used_in_multiple_files
pkg/app/testdata/app_list_test/filters_releases_for_environment_used_in_one_file_only
pkg/app/testdata/app_list_test/list_releases_matching_selector_and_environment

feat: add gotmpl file ext when using helmfile.d feature
closes: https://github.com/helmfile/helmfile/issues/654
@mumoshu haha. I predict it in advance.

feat: add gotmpl file ext when using helmfile.d feature

---

docs/paths.md
examples/deployments/dev/helmfile.yaml
examples/deployments/local/helmfile.yaml
examples/deployments/prod/helmfile.yaml
examples/deployments/published/helmfile.yaml

update examples info

---

docs/index.md

update hooks docs
@mumoshu from the code. I add docs about the order of hooks exec. Please review.

update hooks docs

---

README.md

https://github.com/helmfile/helmfile/discussions/661

Bring up the init command in readme #661

---

docs/proposals/towards-1.0.md

so that we can link to each section easily using "#the-element-id" URL fragment.

Reformat v1 proposal

---

docs/builtin-objects.md
mkdocs.yml

add build-in objects docs

---

README-zh_CN.md

Add chinese readme

---

.github/workflows/ci.yaml
.github/workflows/lint.yaml
.github/workflows/publish_binaries.yaml
.github/workflows/publish_v1_binaries.yml
.github/workflows/test_binary_builds.yaml
Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu
go.mod

Bump Go to 1.20

---

README-zh_CN.md
README.md

Sync Chinese readme

---

pkg/app/app.go
pkg/app/run.go

fix panic issue

---

docs/advanced-features.md
docs/remote-secrets.md
docs/templating_funcs.md
go.mod
go.sum
pkg/app/app.go
pkg/app/app_apply_hooks_test.go
pkg/app/app_apply_nokubectx_test.go
pkg/app/app_apply_test.go
pkg/app/app_diff_test.go
pkg/app/app_lint_test.go
pkg/app/app_list_test.go
pkg/app/app_sync_test.go
pkg/app/app_template_test.go
pkg/app/app_test.go
pkg/app/desired_state_file_loader.go
pkg/app/destroy_nokubectx_test.go
pkg/app/destroy_test.go
pkg/app/diff_nokubectx_test.go
pkg/app/diff_test.go
pkg/plugins/vals.go
pkg/state/create.go
pkg/state/state.go
pkg/state/state_test.go
pkg/tmpl/expand_secret_ref.go

bump vals to v0.22.0

---

pkg/app/two_pass_renderer.go
pkg/state/envvals_loader.go

optimize logger code

---

cmd/root.go

fix cobra issue
```
unknown command "tttt" for "helmfile"
Did you mean this?
test
exit status 3
```
/cc @mumoshu @xiaomudk

fix cobra issue

---

cmd/root.go
docs/index.md

fix: update file help message

---

docs/builtin-objects.md

fix build-in objects docs

---

pkg/tmpl/get_or_nil.go
pkg/tmpl/get_or_nil_test.go

fix get template func
see: https://github.com/helmfile/helmfile/discussions/718

fix get template func

---

pkg/envvar/const.go
pkg/helmexec/exec.go
pkg/helmexec/exec_test.go

clean: helm v2 logic code

---

pkg/state/state.go

fix concurrency issue

---

go.mod
go.sum
pkg/environment/environment.go
pkg/state/create.go
pkg/state/envvals_loader.go
pkg/state/state.go

bump mergo to 0.3.14

---

go.mod
go.sum
pkg/state/helmx.go
pkg/state/state.go
test/e2e/template/helmfile/snapshot_test.go

bump chartify to  v0.14.0

---

.github/workflows/images.yaml

chore(release): add latest tag only on release tags

---

go.mod
go.sum

feat: use offical goccy/go-yaml

feat: use offical goccy/go-yaml

---

pkg/state/release.go
pkg/state/release_test.go
pkg/yaml/yaml.go
pkg/yaml/yaml_test.go

fix: ValuesTemplate quote issue
https://github.com/helmfile/helmfile/issues/786

fix: ValuesTemplate quote issue

---

cmd/root.go
docs/index.md

Add documentation on internal environment variables

---

docs/builtin-objects.md
docs/writing-helmfile.md

While here fix whitespace issues.

Fix inherit examples following #674

---

.github/workflows/images.yaml

chore(release): fix condition for latest tag

---

Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu

Sorry it has taken me a few tries to get this right. These things are a bit of a pain to test.
Fixes #825 by actually emulating the final image

Properly emulated arm64 Docker builds

---

pkg/state/state.go
pkg/state/state_test.go
pkg/state/temp_test.go

Feat: support helm flag --enable-dns

---

pkg/state/create.go
test/integration/run.sh
test/integration/test-cases/v1-subhelmfile-multi-bases-with-array-values.sh
test/integration/test-cases/v1-subhelmfile-multi-bases-with-array-values/input/environments.yaml.gotmpl
test/integration/test-cases/v1-subhelmfile-multi-bases-with-array-values/input/helmfile.yaml.gotmpl
test/integration/test-cases/v1-subhelmfile-multi-bases-with-array-values/input/repositories.yaml
test/integration/test-cases/v1-subhelmfile-multi-bases-with-array-values/input/subhelmfile.yaml.gotmpl
test/integration/test-cases/v1-subhelmfile-multi-bases-with-array-values/input/values.yaml.gotmpl
test/integration/test-cases/v1-subhelmfile-multi-bases-with-array-values/output/result
test/integration/test-cases/v1-subhelmfile-multi-bases-with-array-values/readme

quick fix: https://github.com/helmfile/helmfile/issues/835
future plan: make overrodeEnv as value pass.

fix: loadBases overrodeEnv issue

---

cmd/apply.go
cmd/delete.go
cmd/destroy.go
cmd/sync.go
go.mod
pkg/app/app.go
pkg/app/app_test.go
pkg/app/config.go
pkg/app/destroy_test.go
pkg/config/apply.go
pkg/config/delete.go
pkg/config/destroy.go
pkg/config/sync.go
pkg/state/helmx.go
pkg/state/helmx_test.go
pkg/state/state.go
pkg/state/state_test.go
pkg/state/temp_test.go
pkg/testutil/mocks.go

feat: add cascade support
see: https://github.com/helmfile/helmfile/discussions/859

Feat add cascade support

---

docs/index.md

docs: update cascade

---

pkg/app/app.go

fix extra args missing in helmfile apply subcommand

fix extra args missing in helmfile apply subcommand

---

pkg/app/app.go
pkg/state/state.go
test/integration/run.sh
test/integration/test-cases/chartify.sh
test/integration/test-cases/chartify/input/helmfile.yaml
test/integration/test-cases/chartify/output/template
test/integration/test-cases/chartify/output/template-set

Fix set flag are ignored when used in conjunction with jsonPatches

---

docs/index.md
pkg/state/state.go
pkg/state/temp_test.go
test/integration/test-cases/v1-subhelmfile-multi-bases-with-array-values/input/environments.yaml.gotmpl

cleanup: remove tls configures about helm v2
https://v2.helm.sh/docs/helm/#helm-list

cleanup: remove tls configures about helm v2

---

docs/index.md

chore(docs): fix table

---

docs/index.md

Table not rendering:
Incorrect indentation:

fix(docs): table and list formatting

---

pkg/app/app_list_test.go
pkg/app/app_test.go
pkg/app/formatters_test.go
pkg/testutil/testutil.go
pkg/testutil/testutil_test.go

cleanup: remove panic in testutil

---

pkg/state/state.go
test/integration/test-cases/chartify/input/helmfile.yaml
test/integration/test-cases/chartify/output/template
test/integration/test-cases/chartify/output/template-set

fixes: https://github.com/helmfile/helmfile/issues/895

fix: chartifyOpts ignore release set values

---

pkg/state/storage.go
pkg/state/storage_test.go

fix set-file cannot find the file on windows

---

pkg/state/state.go

see: https://github.com/helmfile/helmfile/issues/915

feat: add --insecure-skip-tls-verify support for helmfile template

---

pkg/app/app_test.go
pkg/exectest/helm.go
pkg/helmexec/exec.go
pkg/helmexec/exec_test.go
pkg/helmexec/helmexec.go
pkg/state/state.go
pkg/testutil/mocks.go

fix: https://github.com/helmfile/helmfile/issues/920

feat: add insecure support for oci repo

---

pkg/app/desired_state_file_loader.go
pkg/state/create.go
test/e2e/template/helmfile/testdata/snapshot/environment_missing_in_subhelmfile/helmfiles/no-envs.yaml
test/e2e/template/helmfile/testdata/snapshot/environment_missing_in_subhelmfile/helmfiles/no-values.yaml
test/e2e/template/helmfile/testdata/snapshot/environment_missing_in_subhelmfile/helmfiles/noEnvs.yaml
test/e2e/template/helmfile/testdata/snapshot/environment_missing_in_subhelmfile/helmfiles/prod.yaml
test/e2e/template/helmfile/testdata/snapshot/environment_missing_in_subhelmfile/input.yaml
test/e2e/template/helmfile/testdata/snapshot/environment_missing_in_subhelmfile/output.yaml

fix: https://github.com/helmfile/helmfile/issues/950 https://github.com/helmfile/helmfile/issues/948

fix re-using environment state in sub-helmfiles issue

---

docs/templating_funcs.md

See https://github.com/helmfile/helmfile/commit/ed436ba68bd80057be99c20296c26dd4996b69dc

Add missing documentation for isFile function

---

.github/workflows/ci.yaml
Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu
pkg/app/init.go

see: https://github.com/helm/helm/releases/tag/v3.13.0

feat: bump helm to 3.13.0

---

pkg/app/app.go
pkg/state/chart_dependency.go
pkg/state/state.go

fixes: https://github.com/helmfile/helmfile/issues/1053

feat: skip deps when installed is false

---

pkg/state/state.go
pkg/state/state_test.go

fixes: https://github.com/helmfile/helmfile/issues/1047

optimize OCI chart version check

---

pkg/policy/checker.go
pkg/policy/checker_test.go

fix issue 1093

---

pkg/state/chart_dependency.go

resolved deps even when installed=false

---

go.mod
go.sum

Support this.
https://github.com/helmfile/chartify/pull/64

Update helmfile/chartify to v0.17.0

---

pkg/policy/checker.go
pkg/policy/checker_test.go

fix: https://github.com/helmfile/helmfile/issues/1147

fix checker for empty array case

---

pkg/state/state.go
pkg/state/state_test.go

fixes: https://github.com/helmfile/helmfile/issues/1220

fix: ConditionEnabled panic issue

---

.github/workflows/ci.yaml

build(deps): bump actions/upload-artifact and actions/download-artifact from 3 to 4

build(deps): bump actions/upload-artifact and actions/download-artifact from 3 to 4

---

cmd/sync.go
pkg/config/apply.go
pkg/config/sync.go
pkg/state/helmx_test.go

Fix typos and add a UnitTest for adding dry runs flag

Fix typos and ask unittest

---

pkg/tmpl/context_tmpl.go
test/integration/test-cases/include-template-func/input/_helpers.tpl
test/integration/test-cases/include-template-func/input/nested/_helpers.tpl
test/integration/test-cases/include-template-func/input/values/_helpers.tpl

fix: https://github.com/helmfile/helmfile/issues/1276

feat: include func support more template functions

---

pkg/helmexec/exec.go
pkg/helmexec/exec_test.go

Bugfix: do not print registry password to stdout when running

---

docs/advanced-features.md

feat: document that jsonPatches et al can be files

---

Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu
go.mod

feat: update to use go 1.22

---

pkg/state/state.go

`isReleaseInstalled` will call `helm list` which can take a bit of time. in order to allow parallelism, we need to use a finer mutex lock.

fix: use finer-grained locking when listing releases for diff

---

pkg/state/state.go
pkg/state/util.go
pkg/state/util_test.go

https://github.com/helmfile/helmfile/issues/1335

fix: version path issue

---

USERS.md

Hi,
@TUDOCK recently started using Helmfile and we like it a lot!
Thank you for creating this project!
---
CC: @theCapypara

Add Tudock GmbH to USERS.md

---

pkg/state/state.go
test/integration/run.sh
test/integration/test-cases/deps-kustomization-i-1402.sh
test/integration/test-cases/deps-kustomization-i-1402/input/helmfile.yaml
test/integration/test-cases/deps-kustomization-i-1402/input/test/kustomization.yaml
test/integration/test-cases/deps-kustomization-i-1402/input/test/test.yml

skip helm dep up for kustomizations

---

pkg/envvar/const.go
pkg/tmpl/context_funcs.go
pkg/tmpl/context_funcs_test.go

see: https://github.com/helmfile/helmfile/blob/main/docs/proposals/towards-1.0.md

remove HELMFILE_SKIP_INSECURE_TEMPLATE_FUNCTIONS for v1

---

pkg/state/chart_dependency.go

Relax the helmfile.lock helmfile binary version constraint

---

docs/experimental-features.md
docs/proposals/towards-1.0.md
mkdocs.yml

See the updated v1 proposal for why we need it now.

v1: Document experimental features

---

README.md
docs/proposals/towards-1.0.md

I and @yxxhero discussed and decided to update the project status in README to reflect the latest status of the project.
We are now inviting Helmfile v1 rc testers!

Update the project status with invitation to v1 rc testers

---

cmd/template.go
pkg/app/app.go
pkg/app/app_template_test.go
pkg/app/app_test.go
pkg/app/config.go
pkg/app/testdata/app_template_test/show-only
pkg/config/template.go
pkg/state/helmx.go
pkg/state/helmx_test.go
pkg/state/state.go

Add a `--show-only` parameter to the `helmfile template` command to pass on to the `helm template` command.

Add helmfile template --show-only

---

USERS.md

Add [Incentive.me](https://app.incentive.me/) to the list of Helmfile users. We use helmfile as the main tool for deploying our Kubernetes workloads since 2021.

chore: add Incentive.me to the list of helmfile users

---

pkg/state/state.go
pkg/state/storage.go
pkg/state/storage_test.go

https://github.com/helmfile/helmfile/issues/1560

fix windows glob issue

---

pkg/app/app.go
pkg/state/state.go
pkg/state/state_test.go

fix: inject KubeVersion and ApiVersions in Chartify rendering

---

pkg/state/release.go

fix: _*.tpl files add whitespace to empty Namespace

---

pkg/app/run.go

resolved: https://github.com/helmfile/helmfile/pull/1664

feat: skip chart prep for local

---

go.mod
go.sum

https://pkg.go.dev/vuln/GO-2024-2963

feat: update golang minor version based on security vulnerability

---

pkg/policy/checker.go

optimize code

---

pkg/app/run.go

Brings back some comment accidentally removed in #1681, with potentially better explanation 😄

Add comment withPreparedCharts

---

docs/index.md
pkg/app/app.go
pkg/app/app_test.go
pkg/app/config.go
pkg/config/apply.go
pkg/config/sync.go
pkg/state/helmx.go
pkg/state/helmx_test.go
pkg/state/state.go

https://github.com/helm/helm/pull/11600

Add   hide notes support

---

go.mod
pkg/app/desired_state_file_loader.go
pkg/environment/environment.go
pkg/hcllang/hcl_functions.go
pkg/hcllang/hcl_loader.go
pkg/state/create.go
pkg/state/envvals_loader.go
pkg/state/state.go
pkg/state/state_exec_tmpl.go

https://github.com/darccio/mergo?tab=readme-ov-file#important-notes

build(deps): bump dario.cat/mergo from 0.3.16 to 1.0.1

---

.github/workflows/ci.yaml
Dockerfile
Dockerfile.debian-stable-slim
Dockerfile.ubuntu
go.mod
go.sum
pkg/app/app.go
pkg/errors/errors.go
pkg/hcllang/hcl_loader_test.go
pkg/helmexec/exec.go
pkg/helmexec/exec_test.go
pkg/helmexec/runner.go
pkg/state/envvals_loader_test.go
pkg/state/state.go
pkg/tmpl/context_funcs.go

This pull request includes various updates and improvements across multiple files, focusing on upgrading dependencies, improving error handling, and minor codebase cleanups.
* Updated `golangci-lint` version from `v1.57.2` to `v1.61.0` in `.github/workflows/ci.yaml`.
* Updated Go version from `1.22` to `1.23` in `Dockerfile`, `Dockerfile.debian-stable-slim`, and `Dockerfile.ubuntu`. [[1]](diffhunk://#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L1-R1) [[2]](diffhunk://#diff-ba602f969c43d8bdc4cbe0c2243476dfcc51f818d28f079418302e94cf7e791aL1-R1) [[3]](diffhunk://#diff-b4c6189f9184e61338a887d10410ec33e466f2fdba640cb632fab869dcb8b289L1-R1)
* Updated Go version from `1.22.6` to `1.23.1` in `go.mod`.
* Replaced `fmt.Fprintln` and `fmt.Fprintf` with error-handling …

feat: update go version and adjust dependencies in Dockerfile and go.mod

---

pkg/state/state.go

- Refs https://github.com/helmfile/helmfile/pull/773

fix: duration of delete failures are always 0s

---

cmd/root.go
cmd/template.go
pkg/app/app.go
pkg/app/app_test.go
pkg/app/config.go
pkg/app/destroy_test.go
pkg/app/diff_test.go
pkg/config/global.go
pkg/state/state.go
pkg/state/temp_test.go

--skip-deps ties together build deps and helm repo update this allows for us to skip the repo up,but still build the deps

[feature] add --skip-refresh to globals

---

test/integration/lib/ensure.sh

Resolves #1768 by using the correct status fields

fix(integration-tests): read correct minikube status (#1768)

---

pkg/state/state.go
pkg/state/state_test.go

closes #1857 
This pull request includes several refactorings and improvements to the `HelmState` methods in the `pkg/state/state.go` file. The changes focus on simplifying the code and improving the handling of flags for Helm commands.
Refactorings and improvements:
* [`pkg/state/state.go`](diffhunk://#diff-7e4e87a1e777423a3d9a915e00fb78a9c4fc2f4c476863f60b67e89b9c635697L2667-R2706): Refactored the `appendChartDownloadFlags` method to use new helper methods `needsPlainHttp` and `needsInsecureSkipTLSVerify`, which encapsulate the logic for determining whether certain flags are needed.
* [`pkg/state/state.go`](diffhunk://#diff-7e4e87a1e777423a3d9a915e00fb78a9c4fc2f4c476863f60b67e89b9c635697L2847-R2881): Updated the `flagsForDiff` method to remove the `--plain-http` flag if it is present, …

fix: ensure plain http is supported across all helmfile commands

---

pkg/state/helmx.go
pkg/state/helmx_test.go

Fixed test to correctly assert the new flag
Fixes changed made in https://github.com/helmfile/helmfile/pull/1863

fix: using correct option for takeOwnership flag

---

docs/index.md

This fixes a typo I noticed while reading the docs

fix typo in docs

---

pkg/config/config.go
test/integration/test-cases/cli-overwrite-environment-values.sh
test/integration/test-cases/cli-overwrite-environment-values/input/values.yaml.gotmpl
test/integration/test-cases/cli-overwrite-environment-values/output/output_v1.yaml

This aim to fix https://github.com/helmfile/helmfile/issues/1900
It would allow to use quoted string value containing any special character and specially ","

Use a regex to match --state-values-set-string arguments

---

docs/requirements.txt

https://security.snyk.io/vuln/SNYK-AMZN2-PYTHONBABEL-5411337

chore: update babel to resolve CVEs

---

pkg/state/state.go

The build command is intended to be a read-only inspection command that outputs the helmfile state. However, when releases use jsonPatches, strategicMergePatches, or transformers, the chart preparation step triggers chartify, which runs helm template and requires dependencies to be built.
This causes two issues:
1. helm template is executed unnecessarily for a simple state inspection
2. Missing chart dependencies cause errors even with SkipDeps enabled
This change modifies PrepareCharts to filter out releases that require chartify when the command is "build". These releases are excluded from chart preparation, preventing helm template from being invoked.
The state output will still include these releases, but their charts won't be processed during the build operation.

fix: skip chartify for build command jsonPatches
